### ISSUE TITLE
Suggestion: Resolution option within nvidia controller

### ISSUE THREAD

**Issue by Kaeroe** [Maassoft/ColorControl#100]
Unless i am being blind, there does not seem to be a way to change resolution within the main control window?
I use this program to control HDR with a hotkey (but on a profile with all the correct settings for my LG G1), but i figure it would be good also for my girlfriend to use this also for changing her resolution so that her drawing tablet works on her ultrawide. There are probably other/better software solutions for this but i think i would also find it quite handy down the line for a more demanding game for example.
Other than that, wonderful software thank you! also really helped with the color gamut on SDR mode :)

And incase anyone is wondering why i dont just use the default windows HDR hotkey, i disabled a lot of the built in xbox related stuff in order to remove the gamebar overlay, and in order to make gamebar relevant, windows seems to have tied the function of hdr to the gamebar

**Comment by Maassoft** [comment]
No, you are right, changing resolutions is not yet supported from this application. I'll investigate whether it will be easy to add this and I think it will be, so maybe the next release will support it.

**Comment by Maassoft** [comment]
Changing resolutions is now supported with v6.0.0.0.
