### ISSUE TITLE
The program doesn't start

### ISSUE THREAD

**Issue by TatsunaKyo** [Maassoft/ColorControl#105]
Hello, first of all thank you for your work.

I've been trying to use this program but no matter what version I download and try to start, it doesn't turn on. Nothing happens, not even when looking at the Task Manager. It's like I didn't even clicked. 
I tried running the app in admin mode but to no avail.
I went as far as to install Npcap even though I read that you advise to do so only in case of WinPcap errors.
Ultimately, I tried to restart Windows and nothing changed. Do you have any idea?

Kind Regards.

**Comment by Maassoft** [comment]
What Windows version are you running?
And have you tried cleaning the folder with the settings?
`C:\Users\username\AppData\Roaming\Maassoft\ColorControl`
Re(move) everything from that folder and try if the program starts.

Npcap is not needed anymore.

**Comment by TatsunaKyo** [comment]
I'm running Windows 10 Home, version 21H2.
Unfortunately, there's no such a folder in the Roaming directory. I don't think the app could've produced any file, I had never used it before and it doesn't even start in the background process when I launch it (whether it is through the .exe or the launcher).

I'll proceed to delete Npcap if it's not.

**Comment by TatsunaKyo** [comment]
Sorry, I didn't mean to close the issue.

**Comment by Maassoft** [comment]
Can you look in the Event Viewer under Windows Logs -> Application if there is an event logged right after you click on ColorControl.exe?
Maybe some of the prerequisites are not installed on your system (.NET 6 or something else).

**Comment by TatsunaKyo** [comment]
It appears the problem was .NET 6 not updated.
It's weird, because I had it installed, it just didn't update even though I'm even with the Windows Updates...
Anyway, now I can run the program. You've been a great help. Thank you for your service and for developing this software -- without you I would've had to buy a remote to access the service menu and shipments in my country are a mess right now. Thank you very much and wish you the best!
