### ISSUE TITLE
Could you guys add the "change Aspect Ratio" option?

### ISSUE THREAD

**Issue by Skaayoo** [Maassoft/ColorControl#111]
Since I play in 1680x720 (low ress ultrawide, so my C9 looks like a ultrawide monitor), I use the All-Direction Zoom option, to put the screen area a bit down, but I only use this resolution when playing some games, when I use my TV for youtube and other purposes, I change back to 4K resolution (using a keyboard shortcut as well) but I need to change the aspect ratio back to original. So, if you guys add the option to change the aspect ratio as well when changing resolutions, it would be perfect.

**Comment by v00d00m4n** [comment]
i want this option too!

**Comment by Maassoft** [comment]
Thanks for the request. I will look into this and probably add it in the next release.

**Comment by Maassoft** [comment]
The Aspect Ratio and Zoom options are added with v7.1.0.0.

**Comment by Skaayoo** [comment]
Thank you so much!!
