### ISSUE TITLE
Feature request: Add 'Auto Volume' in 'Expert' menu.

### ISSUE THREAD

**Issue by AudioDuplication** [Maassoft/ColorControl#115]
Hi, I don't know if this is possible. But please add the "Auto Volume" option to "Expert"
(found in All settings > Sound > Additonal settings > Volume mode > Auto Volume).

I like to toggle this often, but as you can see its quite a few menu's down.
If its not possible I'll just use the macro thingy.

Dankjewel!

**Comment by Maassoft** [comment]
Hi, yes, this is possible. I've just tested the setting "autoVolume" with an "on" or "off" value and I saw it toggling in the UI.
Will be added in the next release.

Graag gedaan!
