### ISSUE TITLE
Service Remote from Webos

### ISSUE THREAD

**Issue by annie-rizvi-b** [Maassoft/ColorControl#129]
Im creating a remote for an LG OLED connected via ethernet for a project. Is there a websocket command that can be sent to access the secret menu/service remote functionality? If not, is there a serial command?

**Comment by Maassoft** [comment]
Yes, via websockets you have to send this command to open the InStart menu:

```
{
   "id":"25",
   "type":"request",
   "uri":"ssap://system.launcher/launch",
   "payload":"{\"id\":\"com.webos.app.factorywin\",\"params\":{\"id\":\"executeFactory\",\"irKey\":\"inStart\"}}"
}
```
This starts the factory app with some parameters. The payload is an embedded json as a string (hence the escaping of double quotes). And the handshake must already been done.

**Comment by annie-rizvi-b** [comment]
Thank you so much. This is insanely helpful and I really appreciate it.
