### ISSUE TITLE
Expert > Backlight/Picture Mode. LG C2

### ISSUE THREAD

**Issue by Battler624** [Maassoft/ColorControl#132]
I broke something up while testing stuff.
I was trying to play Dolby vision videos while on windows and thought maybe forcing that picture mode would make it work. I tried but absolutely nothing happened, so I thought maybe it's a problem with the program so i changed the backlight, it worked but that made me realise that picture mode thing isn't a possible solution. 

Anyway, I stopped with the tinkering there and switched to plex app on the tv and played the movie from there, where it was playing weirdly, at first, I assumed it's a corrupted file so I played something that I knew for sure was good but same problem.

Problem can be seen here https://youtu.be/PIGp60pW2qU

It feels like the backlight is strobing, but I dont know if the term is correct, anyway turning off the PC then turning the TV off and on again makes everything work again. BUT if i turn on the PC again, things get fucked up again, so i'm assuming its a problem with ColorControl.

Is there an Auto setting or reset expert settings button?

This was happening on 7.2 but I just updated to 7.3 and its still happening.

**Comment by Maassoft** [comment]
You can always reset a picture preset with the Reset button in the TV menu (not via Color Control).
That strobing looks a lot like this: https://www.avsforum.com/threads/2022-lg-c2-g2-owners-thread-no-price-talk.3250717/post-62023301

I believe there might currently be an issue with the Dolby Precision Detail setting on the 2022 series. Maybe turning that off will stop the strobing?

**Comment by Battler624** [comment]
> You can always reset a picture preset with the Reset button in the TV menu (not via Color Control). That strobing looks a lot like this: https://www.avsforum.com/threads/2022-lg-c2-g2-owners-thread-no-price-talk.3250717/post-62023301
> 
> I believe there might currently be an issue with the Dolby Precision Detail setting on the 2022 series. Maybe turning that off will stop the strobing?

It did turn it off, but that is so weird because everything works correctly while the PC is off, it only flickers while PC is on. Anyway much thanks for this, i'll keep that thread on lookout.
