### ISSUE TITLE
Feature request: Game Optimiser for C1/C2

### ISSUE THREAD

**Issue by eapiova** [Maassoft/ColorControl#134]
Thanks a lot for this software.

I wanted to ask you if you can implement LG C1/C2's Game Optimiser dashboard and related settings like AMD FreeSync Premium, Prevent Input Delay etc. in Actions and or in the Expert menu.

From what I understand, the GameOptimizationHDMI1-4 action turns Instant Game Response on or off in previous models, but for my C1 it does nothing.

**Comment by Maassoft** [comment]
Yes, these can be added. I'll look into it and they will probably be added in a subsequent release.
