### ISSUE TITLE
TV turns off but never turns on

### ISSUE THREAD

**Issue by MahmoudAlyuDeen** [Maassoft/ColorControl#14]
First of all, **your app is awesome** the features are very well thought out, hat's off from a fellow coder.

I have a small problem getting the app to turn on the TV, when I try to "Test power on/off", the app has no problem turning the TV off, but it doesn't turn on, before or after I hear the click from the TV.

Here's some information about my setup and the steps I did:

1. I downloaded the last version, 1.5.3.0, unzipped, and ran it.

2. As mentioned in the Readme, I got an error when I tried the off/on test, so I downloaded Npcap from the link in the readme and installed it with the default settings

![image](https://user-images.githubusercontent.com/17839198/106913765-a292ec80-6704-11eb-8df1-d3e3d9be5d5f.png)

3. after that, "Test power on/off" worked to turn off the tv, and after hearing the click, and clicking ok to turn the tv on, it didn't do anything.

4. I tried pairing the TV from the settings as mentioned, and I paired 2 devices shown here, **however, the 2 devices disappear from the device manager and are listed in Windows settings as offline when the tv is turned off**

![image](https://user-images.githubusercontent.com/17839198/106914172-0a493780-6705-11eb-9b29-9bceb865f2d1.png)

5. I double-checked the TV settings that mobile on through wifi is enabled, and **I verified that I can turn the tv on from my phone LG TV Plus app as well as AirPlay devices.**

6. I tried another version of Npcap: WinPcap_4_1_3, and I got the same result.

7. I tried the old version, form the readme with different installation options, and got the same results:

![image](https://user-images.githubusercontent.com/17839198/106914617-7cba1780-6705-11eb-9a29-64efa971c6ee.png)

8. I restarted the PC and tried turning off Standby+ from the TV settings, no change.

9. I checked the logs but I didn't find any error messages I could understand, this is the log after I run the on/off test:

2021-02-04 16:25:11.9122|ERROR|ColorControl.MainForm|Error while getting displays: NVAPI_NVIDIA_DEVICE_NOT_FOUND
   at NvAPIWrapper.Native.DisplayApi.EnumNvidiaDisplayHandle()
   at NvAPIWrapper.Display.Display.GetDisplays()
   at ColorControl.NvService.GetDisplays()
   at ColorControl.MainForm.UpdateDisplayInfoItems()
2021-02-04 16:25:21.4516|ERROR|ColorControl.MainForm|Error while getting displays: NVAPI_NVIDIA_DEVICE_NOT_FOUND
   at NvAPIWrapper.Native.DisplayApi.EnumNvidiaDisplayHandle()
   at NvAPIWrapper.Display.Display.GetDisplays()
   at ColorControl.NvService.GetDisplays()
   at ColorControl.MainForm.UpdateDisplayInfoItems()
2021-02-04 16:25:21.4576|DEBUG|ColorControl.WOL|Waking device with MAC-address F8-B9-5A-66-C8-2E
2021-02-04 16:25:21.4576|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_{C4C156C4-2A9F-4CBA-8262-98882D6219EF}
2021-02-04 16:25:21.4576|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_{FD50599C-4EAD-4DB0-BFDA-7D601985CD1D}
2021-02-04 16:25:21.4576|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_{00C3E8CF-5892-4FC5-A037-0FD5E7F05E6E}
2021-02-04 16:25:21.4695|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_{99B49214-F3A3-455E-8493-E18E7FC735B4}
2021-02-04 16:25:21.4695|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_{499ADEBE-C8BC-4412-B0AF-A3C871D6FF67}
2021-02-04 16:25:21.4695|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_{0578BB5D-03CA-4E09-AB62-32CD1FF00B89}
2021-02-04 16:25:21.4695|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_Loopback
2021-02-04 16:25:21.4695|DEBUG|ColorControl.WOL|Opening network device: \Device\NPF_{DAC7B244-E4EC-4480-8EF7-BC85985203F6}

**Comment by Maassoft** [comment]
Thanks for your compliments and elaborate feedback!

I assume this is the MAC-address of the tv: F8-B9-5A-66-C8-2E? You can double check this with the connection settings on the tv. And "Mobile TV On" should be enabled, but that is probably already the case if you can turn it on via an app on your phone. When the tv is turned off and disappears from the Windows device manager, does it reappear if you go to View->Show hidden devices?
Maybe I will improve the logging in a future version so you can see the friendly names of the network devices. The app sends the WOL-packet to all network interfaces of the pc. And maybe I can even remove the dependency of Npcap/WinPcap.

**Comment by MahmoudAlyuDeen** [comment]
Hi, thanks for the prompt response.

I confirmed that the MAC address and IP match the ones listed in the TV's WIFI settings.

And after selecting show hidden devices, both devices appeared with an opaque icon and this message in their properties:

![image](https://user-images.githubusercontent.com/17839198/106946256-2eb70b00-6729-11eb-9c74-d620095354f1.png)

**Comment by MahmoudAlyuDeen** [comment]
Also I don't know if this is related, but I get this error whenever I try to change any of the nvidia related settings:

2021-02-04 16:25:21.4516|ERROR|ColorControl.MainForm|Error while getting displays: NVAPI_NVIDIA_DEVICE_NOT_FOUND
at NvAPIWrapper.Native.DisplayApi.EnumNvidiaDisplayHandle()
at NvAPIWrapper.Display.Display.GetDisplays()
at ColorControl.NvService.GetDisplays()
at ColorControl.MainForm.UpdateDisplayInfoItems()

I would happily assist you debugging that and trying to locate the error since I do have an nvidia 3070 card. but my main personal goal is to get the on/off functionality working along side the amazing macro functionality that emulates magic remote clicks

**Comment by Maassoft** [comment]
Okay, so the tv is still visible in the device manager, but disabled. This is exactly what happens here, so that's good. Whenever the application starts or when you click the "Refresh" button on the LG controller tab it queries the device manager for devices and even disabled devices should be returned. And the fact that you see logging of the WOL-functionality with MAC-address should indicate that it found the tv without a problem. Maybe the WOL-packet is invalid or not send to the right network adapter on your pc. I will add better logging for that.

The Nvidia error you're getting should only be thrown by the Nvidia driver when there's no display attached to the adapter or they're all disabled (turned off). So you even get this when the tv is turned on?

**Comment by MahmoudAlyuDeen** [comment]
I can confirm that the nvidia errors only show when the tv is on and I’m
waiting for an update to test the logging.

If there’s any data I can collect to help you, please let me know.

**Comment by Maassoft** [comment]
I've created a new release with some extra logging when sending WOL-packet. Now you should see the network names and descriptions. Maybe the network device which connects to the tv isn't logged?
Also, if you use any firewall software on your pc, could you temporarily disable it? Maybe the packet gets blocked.

**Comment by MahmoudAlyuDeen** [comment]
Wow, thanks for the quick reaction.

I tried with the latest version and here's the log output:

![image](https://user-images.githubusercontent.com/17839198/107089451-ee29c100-67fe-11eb-8e88-dd384db53115.png)

**Comment by Maassoft** [comment]
Thanks for the log. So your pc and tv are both on that Wi-Fi network? Strange that it reports its description as Microsoft instead of the Intel(R) Wi-Fi description. But maybe that's just Npcap.
By the way, I've looked around and tried some managed code to send a WOL packet and it works. This means that it's possible to do this without the Npcap dependency. I need to do some testing first, but once that's done I will create a new release so you can test it.

**Comment by MahmoudAlyuDeen** [comment]
Perfect. I will test it out once it’s ready. Thanks for the support.

**Comment by Maassoft** [comment]
I've created a new release with the alternate method of sending WOL-packets. Feel free to test it.

**Comment by MahmoudAlyuDeen** [comment]
YES!! That worked perfectly. The TV now turns on when I use the test button.

**Comment by MahmoudAlyuDeen** [comment]
I can't believe that worked even though I'm a programmer myself and I understand that the right packet will wake the TV up, it's just that when I first got the TV, I googled it and it seemed next to impossible to sync the TV to the PC because of how limited HMDI on PC is.

Okay, one last hiccup, but that seems like an easy fix, I hope.

After trying the option to turn the TV on startup and power cycling the PC, it didn't work. 

I also noticed that the checkmarks got cleared after a restart, this is not a new issue, the same thing was happening since 1.5.3.0:

![image](https://user-images.githubusercontent.com/17839198/107144422-57aeea00-693b-11eb-82ae-a40ee4efd7fc.png)

The same thing happened to the "alternative WOL" checkmark.

So even after logging on, and the app starting normally and appearing in the system tray, I had to manually turn on the TV.

Unrelated: I also took a look at the task scheduler, and it says that the app will run **on login, not on startup**, so I'm assuming that regardless of the settings persistence issue, that the app will only run after I've entered my password and logged in, is there an option to make the app run on system startup regardless of the user?

**Comment by MahmoudAlyuDeen** [comment]
I tried quitting the app and reopening it and the settings persist normally, they only get lost after rebooting.

**Comment by MahmoudAlyuDeen** [comment]
Okay, so after quitting the app manually and relaunching it at least once, the settings now persist across reboots. I'd happily assist you to test a fix for that, but for now, I'm okay with quitting and relaunching whenever I change a setting so it persists.

Also, disregard what I said about the task scheduler, the app does launch before logging in.

Now everything works perfectly! The TV turns off on shutdown and back on on startup. Thanks a lot for the amazing support!

**Comment by Maassoft** [comment]
I'm glad it's working for you. I myself have some problems with the new WOL mechanism, but that's because my network adapter seems a bit slow to establish a connection after resume/startup. So the app tries to send the packet when the connection is not yet up, which results in an exception.
I will look into that issue of the checkmarks not saving.
