### ISSUE TITLE
Issue: new option FreesyncOLEDHDMI1-4 not working

### ISSUE THREAD

**Issue by eapiova** [Maassoft/ColorControl#141]
I checked the Game Optimiser dashboard on my LG C1 48 but the new option FreesyncOLEDHDMI1-4 does nothing.

**Comment by eapiova** [comment]
![PXL_20221122_192539490 MP](https://user-images.githubusercontent.com/1353154/203404509-370b8599-9339-412f-99d8-dbb620d9bf84.jpg)
![PXL_20221122_192349985 MP](https://user-images.githubusercontent.com/1353154/203404525-2e82d984-64ea-4668-9a5d-2f32c1394237.jpg)
![PXL_20221122_192413254 MP](https://user-images.githubusercontent.com/1353154/203404531-34e3a70c-c059-4c95-9f9c-e515b0024428.jpg)
![PXL_20221122_192443922 MP](https://user-images.githubusercontent.com/1353154/203404535-91d694d0-1dba-4c80-8154-f7db084f5935.jpg)
![PXL_20221122_192502968 MP](https://user-images.githubusercontent.com/1353154/203404518-1dc2b20b-e6ac-493b-9342-3f20fd1cf009.jpg)

This is the Game Optimiser dashboard for C1/C2, with related settings. As you can see there is only a ON/OFF choice in AMD Freesync. I think that a good feature would be to enable or disable the Game Optimiser dashboard completely, by controlling the on/off button.

**Comment by Maassoft** [comment]
Thanks for the photos. I've added most settings and they will be available in the next update.

**Comment by eapiova** [comment]
Thank you very much for all your work! Really appreciated
