### ISSUE TITLE
Cannot activate HDR Picture profile if Windows is in SDR mode

### ISSUE THREAD

**Issue by vikdean** [Maassoft/ColorControl#145]
**TV:** LG C2
**Software version:** 03.21.30

My issue is, if Windows is in SDR mode, the `pictureMode` HDR steps don't work. I've tried all, `hdr<option>` and `dolbyHdr<option>`, they only work if Windows itself is in HDR mode.

My question is really, whether this is a bug or a limitation of the software, because I know for sure that **mpv** can trigger HDR, even if Windows is in SDR.

**Comment by Maassoft** [comment]
This is a known limitation/intended behavior. All actions on the LG controller tab page only control the TV. You can however include a Nvidia or AMD preset that enables/disables HDR in the steps of a LG controller preset. So if you first enable HDR via a Nvidia preset the HDR picture modes should work.

**Comment by vikdean** [comment]
Is there a documentation somewhere to describe the steps needed to take, to enable that option?

![image](https://user-images.githubusercontent.com/16238514/205374626-a0809b87-dade-425e-9c2e-4b1ee8866b0e.png)

I've looked for it, but couldn't find any details regarding it.

**Comment by vikdean** [comment]
Got it, thanks, managed to make it work.

FYI, if anyone needs this:
1. Override 2 unused profiles in the "NVIDIA/AMD Controller" tab and set it up for HDR and SDR respectively.
Mine looks like this: 
_(keep in mind that I'm on HDMI 2.0, so its set up with certain limitations)_
![image](https://user-images.githubusercontent.com/16238514/205377113-f6a20b15-e879-48b6-8255-fb6944e92857.png)
2. Under "LG Controller" use the NVIDIA profiles as you see fit, e.g.:
An HDR On profile `NvPreset(HDR), pictureMode(hdrGame)` to turn on HDR
And another one with `NvPreset(SDR), pictureMode(Game)` to go back to SDR
