### ISSUE TITLE
LG Flex 42LX3QPUA Support

### ISSUE THREAD

**Issue by tonybweb** [Maassoft/ColorControl#147]
I just got this TV/monitor and found this promising application while searching. I believe the OS/panel are similar to the C1/C2.  However, as it stands now it appears this project doesn't detect/recognize the 42LX3QPUA.

Any plans to support it ? Am I being a bonehead and missing a config detail? I tried directly entering the TVs local IP address after auto detect failed, wasn't successful.

**Comment by tonybweb** [comment]
webOS TV Version
7.2.0-44 (mullet-marine)

Software Version
03.21.30

**Comment by chros73** [comment]
In the recent webos firmwares of 2022 models there are even config values to change the shape of the screen.

You have to enable the remote connection on the TV.

**Comment by Maassoft** [comment]
Yes, probably the remote interface is disabled and therefore you can't connect to it.
What happens if you go with a browser to the TV's IP address, port 3000?
Example:
`http://192.168.178.33:3000/`

Here I get a "Hello world" message.

**Comment by tonybweb** [comment]
When I try to access the IP address of my TV directly it doesn't work. How do I enable this remote interface? I've gone through all the menus many times, I'm not seeing an option for it?

**Comment by tonybweb** [comment]
Just an update here, I got it working. It turned out to be a wifi routing issue on my end.
