### ISSUE TITLE
Feature request: keyboard shortcut to send WOL to the TV

### ISSUE THREAD

**Issue by MahmoudAlyuDeen** [Maassoft/ColorControl#15]
After getting a huge quality of life jump since I found your app, I got determined to not have to use the remote again.

So I finally found a use for the 6 macro keys on my Logitech G613 keyboard and I mapped the volume/brightness/HDR/game/filmmaker/power save off/on/and power off

The only thing I couldn't map to the keyboard is the wake on LAN, I wish I had C# experience so I could've made a PR instead of an issue.

**Comment by Maassoft** [comment]
Thanks for the suggestion. I will look if I can add some other actions (besides the existing remote control buttons) to the popup menu of the "Add button" button. That way you can integrate it with other steps (if necessary).

**Comment by Maassoft** [comment]
I've created a new release which contains this feature. Let me know if it works.

**Comment by MahmoudAlyuDeen** [comment]
Wow, thanks. that was fast!

I'm not going to be home until next Monday unfortunately... so I can't try
it until then.

I'll let you know once I can try it.

**Comment by MahmoudAlyuDeen** [comment]
Works beautifully. Thanks again!
