### ISSUE TITLE
NVAPI_NOT_SUPPORTED Error

### ISSUE THREAD

**Issue by aaronth07** [Maassoft/ColorControl#16]
`2021-02-23 01:53:54.2492|ERROR|ColorControl.GraphicsService|SetColorData threw an exception: NVAPI_NOT_SUPPORTED`

It says that any time I hit apply.

**Comment by Maassoft** [comment]
What are the exact settings you're using? Some combinations of settings are not supported. Most color spaces, for example, will throw this error. Setting dynamic range to VESA while using YUV4XX will also result in this error. Best to leave most settings at Auto first.

**Comment by Maassoft** [comment]
Closing due to no response.
