### ISSUE TITLE
Cross-platform version?

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [Maassoft/ColorControl#164]
Hey :)

This is a pretty awesome tool - thank you! Shortcut keys to control the backlight level of my LG TV? Oh yeah, me likey :)

Is there any way to make this work on Linux and/or macOS using mono? I'm using High Sierra and Fedora.

Cheers :) XOXO

**Comment by Maassoft** [comment]
No, currently it does not work on other platforms besides Windows, see #157
There are too many dependencies on Windows now, but maybe a stripped down version with some features removed could work.

**Comment by DanielSmedegaardBuus** [comment]
Alright :) Thanks for responding!
