### ISSUE TITLE
LG C2 unable to connect to the device

### ISSUE THREAD

**Issue by VEWION** [Maassoft/ColorControl#169]
Unable to connect to C2.
Checked Settings -> General ->Devices -> External Devices -> TV On With Mobile -> Both two options are on. I have tried re-enable both two options, removing device in ColorControl and adding to manually, reinstalling Windows OS, using Settings -> General -> System -> Reset to Initial Settings on C2 and rebooting router but it still doesn't work. Same thing happens on LGTVCompanion too. Don't know if it is related to the recent firmware update 03.30.16.
![螢幕擷取畫面_20230117_182759](https://user-images.githubusercontent.com/56110451/212983044-8ab93d8e-422c-4c05-9478-d03022310c05.png)
![螢幕擷取畫面_20230117_182803](https://user-images.githubusercontent.com/56110451/212983054-dbbe6dd5-f1b0-4306-b8f8-bb05ed9ed6d2.png)

**Comment by Dazog** [comment]
https://www.avsforum.com/threads/2022-lg-c2-g2-owners-thread-no-price-talk.3250717/page-410#post-62270044

Lg did it on purpose.

**Comment by TheRealBix** [comment]
Same issue here, cannot connect to the TV anymore. Hopefuly this can be fixed... Otherwise I'll try to downgrade the firmware

**Comment by Dazog** [comment]
LGTVCompanion dev has figured out how to play nice with LG's update.

So I presume this app will be working again.

**Comment by chros73** [comment]
bscpylgtv is also updated.

**Comment by Maassoft** [comment]
New version of ColorControl (v8.4) is now also available. Please let me know if it works!
https://github.com/Maassoft/ColorControl/releases/tag/v8.4.0.0

**Comment by TheRealBix** [comment]
Yeaaah perfect, here it works.

**Comment by VEWION** [comment]
It's working great! Thank you!

**Comment by aaron-manning** [comment]
Thank you for fixing this. Working great for me
