### ISSUE TITLE
LG: AI Picture Settings (AI Picture Pro, AI Brightness, AI Genre Selection) missing

### ISSUE THREAD

**Issue by P40L0X** [Maassoft/ColorControl#170]
Just wanted to say thanks for this INCREDIBLE tool, but some useful LG options as AI Picture Settings are missing.

More specifically:

-AI Picture Pro
-AI Brightness
-AI Genre Selection

It could be very useful forcing them ON even in PC Mode (for example when ALLM is triggered for Movies), so I hope to see them added as well in the near future.

**Comment by Maassoft** [comment]
Thanks, they will be available in the next release.

**Comment by P40L0X** [comment]
> Thanks, they will be available in the next release.

This is fantastic, thank you!

**Comment by combineclub** [comment]
Fantastic news!

**Comment by Maassoft** [comment]
You can find these settings now in v8.5.0.0.

**Comment by infonator07** [comment]
Well, sadly, it doesn't seem to work at all. 
I can only see AI Brightness even on 10.2.0.0 for some reason :(. 
I had it show up for a moment, but then it disappeared... Please help!
