### ISSUE TITLE
LG: TruMotion -> "Cinematic Movement" missing

### ISSUE THREAD

**Issue by P40L0X** [Maassoft/ColorControl#171]
Just wanted to note that even if TruMotion is actually supported by the tool, I only see "Cinema Clear" but not the new "Cinematic Movement" option LG introduced with 2021-2022 series, which is an upgraded version of interpolation/smoothing with no soap opera effect.

It could be very useful to have it as well, for example forcing it enabled even in PC Mode (for example when ALLM is triggered for Movies), so I hope to see it added as well in the near future.

**Comment by Maassoft** [comment]
I'll add this to the next release as well.

**Comment by P40L0X** [comment]
> I'll add this to the next release as well.

Many thanks!

**Comment by Maassoft** [comment]
You can find this option now in v8.5.0.0 (CinemaClear, technical name).
