### ISSUE TITLE
LG: Dolby Vision "Precision Detail" setting missing

### ISSUE THREAD

**Issue by P40L0X** [Maassoft/ColorControl#172]
I would like to notice that also the new Dolby Vision "Precision Detail" setting (introduced on newer series) is currently missing on ColorControl, which could be super useful to forcefully enable outside DV "Cinema Home" preset and/or when using PC Mode in particular scenarios (for example when ALLM is triggered for Movies).

Thank you again for your amazing work with the app!

**Comment by P40L0X** [comment]
P.S.
See here from min 3:18 where exactly to find and enable the setting (on 2022 Series):

https://www.youtube.com/watch?v=QEfyNxbNC0c

**Comment by P40L0X** [comment]
This would be the last thing I need to "perfectly" setup my LG TV in PC Mode + ColorControl, so PLEASE also support this... :)

Thank you again,
-P

**Comment by Maassoft** [comment]
You can find this option now in v8.5.0.0.
