### ISSUE TITLE
[Question/advice] Dithering and Bitdepth setting

### ISSUE THREAD

**Issue by user18081972** [Maassoft/ColorControl#174]
Considering I am using a 3080 and C9. Should I set the Nvidia bitdepth to 10 or 12bit?
And Nvidia dithering, what should this be set to (in your opinion), on/off 6bit/8bit/10bit?

I am asking you because I have more reason to take your advice, than random self proclaimed experts on Reddit.

**Comment by Maassoft** [comment]
For SDR, a color bit depth of 8 or 10 is enough. Temporal dithering looks the best at 6-bit (most effective) on my C9. If you notice the temporal noise, set dithering bit depth to 8-bit.
For HDR, a color bit depth of minimal 10 bit is needed to reduce most banding. Temporal dithering at 8-bit seems to be the best to remove remaining banding. 6-bit introduces a lot of "noise" and should probably not be used then. The differences between a color depth of 10 or 12-bit are hard to see, just choose what works (no signal blackouts) and looks best on your system and TV.

**Comment by user18081972** [comment]
Great, when testing all the dithering options myself I came to the same conclusion with SDR. I don't use HDR because its too bright for me, i use OLED Light 0 always.
Thanks for your input and explanation!
