### ISSUE TITLE
Unable to execute any command on LG C7

### ISSUE THREAD

**Issue by Bezbashni** [Maassoft/ColorControl#175]
![2](https://user-images.githubusercontent.com/110776155/217416291-47305b24-d814-456a-baba-50a544c6923d.png)
![1](https://user-images.githubusercontent.com/110776155/217416323-f0b67bbd-ed67-4b88-bc23-4ca7023a3359.png)

**Comment by P40L0X** [comment]
Push "BACK" on the physical remote (when you see the white box appear) instead of "OK/Enter" and commands will work ;)

**Comment by Bezbashni** [comment]
> Push "BACK" on the physical remote (when you see the white box appear) instead of "OK/Enter" and commands will work ;)

![1](https://user-images.githubusercontent.com/110776155/217598219-0de822ad-fe79-43e2-81d9-6831adb26322.png)
![2](https://user-images.githubusercontent.com/110776155/217598261-0fa3e261-0224-4df7-a329-09aa32fc7c3b.png)

Not working.

**Comment by P40L0X** [comment]
Try manually adding the C7 with both IP and MAC addresses instead of auto-detect first.

**Comment by Bezbashni** [comment]
> Try manually adding the C7 with both IP and MAC addresses instead of auto-detect first.

Strange i idid it before but this time it worked. Thanks.
