### ISSUE TITLE
I cannot make LG Presets work in GameLauncher Steps

### ISSUE THREAD

**Issue by ravensergio** [Maassoft/ColorControl#176]
Hi. I don't know if I am missing something, but none of my LG profiles work in Pre-Launch,Post-launch etc in GameLauncher.
I tried also making a dummy, (notepad++) and as pre-launch OR post-launch to press the MENU button, or Change brighness ( already setup via profiles in LG.
For example this LG Profile:
![image](https://user-images.githubusercontent.com/32698066/217643965-d50f60d4-204a-4114-b6fd-6ec4aa3ef859.png)

Does not work in a Game Launcher profile, like:
![image](https://user-images.githubusercontent.com/32698066/217644254-6ed15522-30cd-4ca1-a12c-a2f416ecd93e.png)

I also tried in other "real" game profiles, also other LG Profiles as steps, they change nothing. BUT, all the nVidia profiles are working as Steps in Game Launcher. Also, ALL my LG profiles are also working if i start them with "Launch" or via the "Quick Access" launcher (which I love love btw) .
I don't know if I have to do a specific thing. Thank You for everything.

**Comment by user18081972** [comment]
I can confirm this is also not working for me. (I usually dont use this feature, just fyi)

Steps to reproduce (hopefully):
1. ColorControl 8.4.0.0
2. Any of the elevation methods, doesnt matter
3. Add a game launcher entry
4. Point it to any .exe file/uri path
5. Set a pre-launch step via the "Add Step" button.
6. Restart ColorControl (just in case, this app is a little wonky with applying new settings sometimes)
7. Launch the Game launcher preset you made from either the app, or the tray icon.
Result:
A process for the specified .exe is launched, but no presets or any LG TV related changes are applied.
Literally just the process is started.

I would send the logs but no new log entries get logged when launching from the 'game launcher' feature.

**Comment by Maassoft** [comment]
I've just released v8.5.0.0 which fixes this problem.
I was on the brink of releasing a new version and saw this bug report. After investigation a piece of code was missing, so no wonder it didn't work 😄

**Comment by ravensergio** [comment]
Thanks. I will download manually and update then report if is ok ( I'm sure it is). Update from the app seems broken for me
![image](https://user-images.githubusercontent.com/32698066/217918641-0a76aec9-7e70-424e-abe4-85c7d0cc091b.png)

**Comment by ravensergio** [comment]
All seems fine now, I checked a game profile ( and applied A DynamicHDR tonemapping LG profile) .Everything is peachy. 
Thank You.
