### ISSUE TITLE
LG C1/G1: AI Brightness doesn't change/work on Dolby Vision Cinema and Game presets

### ISSUE THREAD

**Issue by P40L0X** [Maassoft/ColorControl#178]
As for the title, I would like to report that using the latest 8.5.0.0 version of the app with both a C1 and G1: force-enabling AI Brightness when using Dolby Vision "Cinema" preset or Dolby Vision "Game" preset (in "PC Mode" or PC HDMI Icon) doesn't work.

The command goes in but doesn't apply, AI Brightness doesn't change.

Is this a preset limitation or an app issue?

Thanks again for your incredible work @Maassoft !

Cheers,
-P

**Comment by Maassoft** [comment]
I think this might be just the TV ignoring this setting while in PC mode. Not all commands that are send to the TV are processed in all HDMI modes. A lot of them fortunately are, even when they are disabled in the menu, but some of them are not. This is probably just a TV limitation.

**Comment by P40L0X** [comment]
> I think this might be just the TV ignoring this setting while in PC mode. Not all commands that are send to the TV are processed in all HDMI modes. A lot of them fortunately are, even when they are disabled in the menu, but some of them are not. This is probably just a TV limitation.

I understand. Thank you again for your answer and for all your work.
