### ISSUE TITLE
LG C1/G1: TruMotion "Cinematic Movement" doesn't work when on PC Mode / PC HDMI Icon

### ISSUE THREAD

**Issue by P40L0X** [Maassoft/ColorControl#179]
As for the title, I would like to report that using the latest 8.5.0.0 version of the app with both a C1 and G1: force-enabling TruMotion "Cinematic Movement" (CinemaClear technical name) or any other TruMotion setting doesn't work when the TV is set to PC Mode (or PC HDMI Icon).

The command goes in but doesn't apply, TruMotion setting doesn't change and remains to "Off".

Is this a preset limitation (when on PC Mode) or an app issue?

Thanks again for your incredible work @Maassoft !

Cheers,
-P

**Comment by Maassoft** [comment]
Like in the other issue, this is most likely a TV limitation. All TruMotion functionality (except Motion Pro) seem to be disabled in PC mode and cannot be enabled.

**Comment by P40L0X** [comment]
> Like in the other issue, this is most likely a TV limitation. All TruMotion functionality (except Motion Pro) seem to be disabled in PC mode and cannot be enabled.

I understand. Thank you again for your answer and for all your work.
