### ISSUE TITLE
Add support for ignoring computer WOL events

### ISSUE THREAD

**Issue by aabdellah** [Maassoft/ColorControl#18]
I think it would be good to have an option to not wake the TV when the computer is waken using WOL so that if the computer is activated remotely the TV doesn't turn on for example.

**Comment by Maassoft** [comment]
Thanks for the suggestion. It will however be a challenge to detect if the pc has been woken by WOL. What option wakes the pc now, is it the power on after startup or after resume?

**Comment by aabdellah** [comment]
That's true, I did some investigation on event viewer and I only find the USB device name responsible for the wake and sometimes it's the name of the interface.
I have both enabled.

**Comment by Maassoft** [comment]
In the new version 2.1.0.0 I've tried to detect if the user is logged on locally or remote. WOL will now no longer be send to the tv if the local "console" session has been disconnected.
