### ISSUE TITLE
Can't start service

### ISSUE THREAD

**Issue by AtomicDude** [Maassoft/ColorControl#186]
![image](https://user-images.githubusercontent.com/49509282/223288136-52bbaa5f-f221-44e0-844d-6b8e6a967e8e.png)
I'm getting this error when I'm trying to start the Service needed for the Elevation-method.
Windows 11.

**Comment by Prouk** [comment]
Same here, tried with multiple .NET ver. still same, tried on 8.4.0.0 too, still same...

**Comment by Maassoft** [comment]
That's strange. There's a check that it only tries to start the service if there are administrator rights. If not, a temporary elevated process is started to start the service (which might cause a User Account Control popup).
Do you get this error when manually clicking the Start button or do you get a popup that the service is not running?
The problem should however remedy itself if the service is installed properly and you restart Windows, the service should start then automatically.

**Comment by AtomicDude** [comment]
Hello, I was getting the pop up when I was trying to select the elevation method (service wasn't installed). After the service was installed it wouldn't automatically start (the pop up showed up) and if I tried to start it manually, I would also get the pop up. I'm pretty sure I tried both with and without running the program as an administrator.

Now it's working as expected for some reasons, I'm no longer getting the pop up.

**Comment by vpark** [comment]
I'm was also seeing the same issue but then realized that the service wasn't running as I changed the location of the executable when I was manually upgrading from 8.x.0.0 to 9.x.0.0. @AtomicDude @Prouk, you should check to see if the binPath of "Color Control Service" in services indeed in the right dir.

if not run `sc config "Color Control Service" binPath= "C:\Users\username\yourdir\ColorControl.exe"` in command prompt and start the service again `sc start "Color Control Service"`

**Comment by Prouk** [comment]
Sry for the absence of response, it's been working great since then 👍
