### ISSUE TITLE
[Feature Request] Assignable shortcut for Game Bar

### ISSUE THREAD

**Issue by AkitoFire** [Maassoft/ColorControl#190]
As an LG OLED owner, I totally love this software! One additional feature that would be really cool would be the option to assign a shortcut for the "Game Bar". Being able to open up that quick settings menu from other apps or even maybe fullscreen applications would be very useful, for me at least.

**Comment by AkitoFire** [comment]
Sorry, based on a comment I saw on another issue it seems like it's already possible to open up the game bar via a keyboard shortcut. But I haven't found that shortcut yet and there's apparently no info in the app itself.

**Comment by Maassoft** [comment]
You can set the shortcut on the Options tab. In the group box "LG controller" there is a "Game Bar shortcut" input field which allows you to specify a shortcut.
This works in most applications, but may have some issues with games using exclusive full screen and/or some games blocking certain keys.

**Comment by AkitoFire** [comment]
Thank you so much! I'm so sorry for missing that option, I somehow overlooked it.
