### ISSUE TITLE
Cannot connect to LG C2 after switching to v9.0.0.0

### ISSUE THREAD

**Issue by vikdean** [Maassoft/ColorControl#193]
After updating ColorControl to v9.0.0.0, it cannot reach my LG C2; power on startup works, but nothing else.

Error from log:

> 2023-04-02 09:44:33.9667|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection with [LG] webOS TV OLED42C21LA...
> 2023-04-02 09:44:33.9667|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.62:3001
> 2023-04-02 09:44:33.9667|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.62:3001/: 0x80072EFD
> 2023-04-02 09:44:34.4704|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
> 2023-04-02 09:44:34.4704|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection result: False

"If a tv is powered on, it will show a popup by which you can allow ColorControl to send commands to you tv" -> This didnt happen; is there a way to trigger it? I've tried to delete the connection history on the TV, but nothing happened.

**Comment by Maassoft** [comment]
I'm seeing the error '0x80072EFD' in the log, which means something like this:

```
The error 0x80072efd may be caused by an interference of the firewall of the computer or the local network while connecting to the server. It could also be that your PC has lost its internet connectivity, or that the network has limited access.
```

Have you tried removing the device from ColorControl (if added manually) and/or adding the device manually again? Maybe the IP-address changed or something in the network is blocking access.

**Comment by vikdean** [comment]
Its and automatic device, wasn't added manually. IP Address is the same as before.
I've opened the 3001 port in my Router, also added to whole ColorControl folder to the Firewall whitelist but same issue.
It was working fine with v8.4.0.0; I did nothing else just replaced the 2 versions.

The connection itself works btw:

> Test-NetConnection 192.168.1.62 -p 3001
>
> ComputerName     : 192.168.1.62
> RemoteAddress    : 192.168.1.62
> RemotePort       : 3001
> InterfaceAlias   : Ethernet
> SourceAddress    : 192.168.1.39
> TcpTestSucceeded : True

The issue definitely seem to be that popup I'm not getting on the TV. Is there a way to trigger that?

**Comment by vikdean** [comment]
Okay, stopped v9.0.0.0, went back to v8.4.0.0, got the popup, approved it. Quit v8.4.0.0 and started to v9.0.0.0. Issue remains the same...

> 2023-04-02 22:15:28.1129|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.62:3001/: 0x80072EFD
> 2023-04-02 22:15:28.6282|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
> 2023-04-02 22:15:28.6282|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection result: False
> 2023-04-02 22:15:29.6426|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection with [LG] webOS TV OLED42C21LA...
> 2023-04-02 22:15:29.6426|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.62:3001
> 2023-04-02 22:15:29.6426|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.62:3001/: 0x80072EFD
> 2023-04-02 22:15:30.1307|ERROR|ColorControl.Services.LG.LgPanel|System.InvalidOperationException: Not connected
>    at ColorControl.Services.LG.LgDevice.CheckConnection() in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgDevice.cs:line 752
>    at ColorControl.Services.LG.LgDevice.GenericPictureAction(Dictionary`2 parameters) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgDevice.cs:line 1013
>    at ColorControl.Services.LG.LgDevice.ExecuteAction(InvokableAction action, String[] parameters) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgDevice.cs:line 713
>    at ColorControl.Services.LG.LgPanel.btnLgExpertColorGamut_Click(Object sender, EventArgs e) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\LG\LgPanel.cs:line 982
> 2023-04-02 22:15:30.1855|DEBUG|ColorControl.Services.LG.LgDevice|Cannot apply LG-preset: no connection could be made
> 2023-04-02 22:15:30.1855|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection result: False
> 2023-04-02 22:15:30.1855|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.62:3001
> 2023-04-02 22:15:30.1855|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.62:3001/: 0x80072EFD
> 2023-04-02 22:15:30.7034|ERROR|LgTv.LgTvApiCore|Connect to wss://192.168.1.62:3001/: 0x80072EFD
> 2023-04-02 22:15:31.2017|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection with [LG] webOS TV OLED42C21LA...

So yeah, this confirmed it, that the issue is with v9.0.0.0

**Comment by TommyCreo21** [comment]
Version 9.0.0 was working fine for me after updating.

But then I installed a new router, and my TV got a new IP address. I removed the TV and re-added it in CC, but it wouldn't turn it on and off like it was supposed to. Every time I restarted CC, it forgot all the settings for when to turn the TV off and on.

I reverted back to 8.5.0 and re-added the TV. Now it worked again. I then updated to 9.0.0 and it still worked.

Seems something is not quite working right in 9.0.0 when adding a device.

**Comment by vikdean** [comment]
Yeah the "power on after startup" doesnt work for me either. 
![image](https://user-images.githubusercontent.com/16238514/231011516-64c3af94-562c-4ac2-8d2e-c1fe344e39e9.png)
If I set it, it looks good, but it unchecks itself after a reboot.
