### ISSUE TITLE
ColorControl is unable to turn the TV off if a screensaver is playing before Windows turns the display off.

### ISSUE THREAD

**Issue by GTMoraes** [Maassoft/ColorControl#194]
Hey there!

ColorControl is able to turn off/on my TV if I don't setup a screensaver, set it to turn the TV off when Windows turn the display off, and just setup the "Display Off" time on Windows Power Settings.
Same thing if I use a blank screensaver and ask for ColorControl to turn the display off if the Screensaver comes on.

However, if I use a screensaver AND the Windows Power Settings "Display Off" in tandem, like Screensaver kicking in after 3 minutes of inactivity, and "Display Off" after 15 minutes of inactivity, and set up to ColorControl to turn the TV off when Windows turns the display off, it doesn't turn the TV off.

After the 15 minutes of inactivity (while the screensaver is playing), Windows turns the display off. And the issue here is that ColorControl doesn't turn the display off, as it was set up to do.
ColorControl will, however, turn the display ON, if it was turned off automatically by the TV itself, after a while on the "No signal" screen.

I cleared the logs, minimized the program and immediately let go of the computer, so it idled at that moment.
I set the screensaver to come up after one minute, and display off after three minutes.
Here's the log file:

> 2023-04-02 12:09:18.9757|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-02 12:09:18.9757|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-02 12:09:19.0017|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-02 12:09:19.0017|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-02 12:09:19.0017|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-02 12:09:19.0017|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-02 12:11:16.9215|DEBUG|ColorControl.MainForm|PBT_POWERSETTINGCHANGE: 2
> 2023-04-02 12:11:27.1610|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] PictureSettingsChanged: {"brightness":"50","contrast":"85","backlight":90,"color":"60"}
> 2023-04-02 12:11:28.9389|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-02 12:11:28.9389|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-02 12:11:28.9597|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-02 12:11:28.9597|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-02 12:11:28.9597|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-02 12:11:28.9597|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-02 12:11:58.3373|DEBUG|ColorControl.MainForm|PBT_POWERSETTINGCHANGE: 1
> 2023-04-02 12:11:58.3373|DEBUG|ColorControl.Services.LG.LgDevice|WakeAndConnectWithRetries: attempt 1 of 10...
> 2023-04-02 12:11:58.3985|DEBUG|ColorControl.Services.LG.LgDevice|WOL succeeded
> 2023-04-02 12:11:58.9119|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://10.0.0.154:3001
> 2023-04-02 12:12:00.0669|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"subscribed":true,"returnValue":true,"state":"Active"}
> 2023-04-02 12:12:00.0669|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-02 12:12:00.0832|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] PictureSettingsChanged: {"contrast":87,"backlight":100,"brightness":52,"color":65}
> 2023-04-02 12:12:00.0832|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] ForegroundAppChanged: {"appId":"com.webos.app.hdmi4","subscribed":true,"returnValue":true,"windowId":"","processId":""}
> 2023-04-02 12:12:00.0832|DEBUG|ColorControl.Services.LG.LgDevice|Connect succeeded: True
> 

ColorControl is running as a service. ColorControl successfully turns the TV off if I set it to turn the TV off when the Screensaver comes up OR if Windows turns the display off.            
With a Screensaver set up AND Windows set up to turn the display off afterwards, AND ColorControl configured to turn the TV off as soon as Windows turns the display off, ColorControl is unable to turn the TV off.

[Screenshot from LG controller](https://i.imgur.com/P2tsjEQ.png)

I'll be happy to help in any way to make ColorControl work as expected, which is to turn off the display when Windows turns the display off.

**Comment by Maassoft** [comment]
Thanks for the detailed report. I'll look into this.
Personally I'm not using the Windows power settings, but just the power off/on when screensaver activates. This works well, even after manually engaging the blank screen saver. After the timeout, the "real" screensaver activates and the TV turns off.
There is one condition that doesn't seem to work on my C9: if I manually activate the Energy Saving option "Screen Off" (on the TV itself), the TV doesn't seem to respond to power off messages send by ColorControl.

**Comment by GTMoraes** [comment]
I'm running a couple of tests here, and found a new bug.

On 9.0.0.0, it seems that I cannot change any of the power on/power off settings on LG Controller tab. Currently, only these are enabled, as I enabled them previously:
- Allow triggers to be fired for this device
- Use Windows power settings to power on
- Use Windows power settings to power off
- Use secure connection

If I enable any other option, or disable any of the enabled options, then press "Refresh" or restart ColorControl, it reverts to the previously enabled settings and disables everything else.            
If I don't press the Refresh button or restart ColorControl, and just disable the "Use Windows power settings to power on/off", the TV will still turn off/on if the Windows power setting to turn screen off kicks in.           
Something seems to be preventing it from changing previous settings. I've tried starting ColorControl as Administrator and as a normal user, but the results are the same.
             


So, in short, there are two problems here, that I noticed:
1) Power off/on settings on LG Controller tab aren't saving
2) ColorControl's option to "Use Windows power settings to power on/off" won't work if there's a screensaver running when Windows turns the display off. 

ColorControl is running a service to invoke commands. I've tried changing to "Run as Admin", but it didn't change the results.
I've tried reinstalling ColorControl (extracting the 9.0.0.0 .zip file to a new folder, turning off the "old" 9.0.0.0 .exe, renaming the %APPDATA%/Maasoft/ColorControl to ColorControl.old, and then firing up the newly extracted 9.0.0.0 .exe) and, this time, only "Allow triggers to be fired for this device" and "Use secure connection" options were enabled.            

**Going back to 8.5.0.0, it now works and these settings are properly saved now. And if I set it to turn off when the screensaver comes up, it will successfully turn the display off as soon as the screensaver comes on.**

I suppose there's a bug on the 9.0.0.0 build that these settings aren't being written, and not being applied.

However, ColorControl still won't turn the TV off after Windows turns the display off while a screensaver is running, unfortunately, so the original issue persists.

Which is, that even though it successfully turns the TV off/on if the Windows power settings turns it off, it won't work if a screensaver was playing before the Windows power setting turns the display off.  

So, for some reason, if there's no screensaver set (screensaver set to "(None)"), when Windows turns the display off, ColorControl will successfully turn the TV off, and will successfully turn the TV on when there's an input.
But if there's a screensaver playing before the TV is turned off by Windows, ColorControl won't detect the off event, and won't pick up that it's supposed to turn the TV on when there's an input (differently from what I originally reported. It doesn't turn the TV on in that case.)

**Comment by Maassoft** [comment]
Thanks for testing.
You're right about the first bug, the settings of the checklist box aren't saving and this was introduced with 9.0.0.0.

The screen not turning off seems to be a Windows issue though. I've been testing the screensaver with a timeout of 1 minute and "turn off my screen after" 2 minutes, but then the power broadcast message is not send by Windows. It seems the screensaver is interfering with this power setting. If I manually start the "blank" screensaver, Windows will still send the message and ColorControl turns the screen off. Windows even gives a warning about the screensaver being active under "Energy recommendations", so it looks like they're aware that the screensaver may be preventing the screen from powering off.

I don't know how to fix this other than introducing a new setting to turn off the screen after X minutes of "screen saving". Will this help your case?

**Comment by GTMoraes** [comment]
> I don't know how to fix this other than introducing a new setting to turn off the screen after X minutes of "screen saving". Will this help your case?

If it's like how I'm thinking, that ColorControl would turn the TV off after X minutes of the screen saver playing, then be able to turn the TV on when I add some input, then 100%! It's exactly the expected behavior that I'm looking for.

In the end, all I want is it to turn the TV off after X minutes of the screensaver playing, and when I move my mouse, for the TV to turn itself on.

**Comment by Maassoft** [comment]
v9.1.0.0 now contains a setting to power off after a configurable number of seconds after the screensaver started.
Let me know if it works on your end.

**Comment by GTMoraes** [comment]
This setting is exactly what I needed. Thank you!

**Comment by evertonmdz** [comment]
"However, if I use a screensaver AND the Windows Power Settings "Display Off" in tandem, like Screensaver kicking in after 3 minutes of inactivity, and "Display Off" after 15 minutes of inactivity, and set up to ColorControl to turn the TV off when Windows turns the display off, it doesn't turn the TV off." 

Same problem here in Samsung S90c, Can you create this option to turn off the TV after a few minutes screensaver for Samsung too? Thanks!! @Maassoft

**Comment by evertonmdz** [comment]
I had to disable everything I did because I was turning off the TV, when it was on another HDMI input on the TV lol, I just left it to turn on the TV when I move the mouse, and the function that does this is "windows power settings to power off" lol as I said above the functions are switched!

![image](https://github.com/user-attachments/assets/3d277d4a-157b-453f-8e4d-e5993f829936)
