### ISSUE TITLE
LG 2022-2023 OLEDs: Real Cinema and/or TruMotion enabling in "non-Game" presets when in "PC Mode" or "4:4:4 Pass Through" Mode

### ISSUE THREAD

**Issue by P40L0X** [Maassoft/ColorControl#195]
Hi,
I just wanted to know if there is a way to properly force enable Real Cinema / Cinema Screen and TruMotion set to "Cinematic Movement" (which is called "cinemaClear" in ColorControl options under TruMotion) for LG 2022 and also new 2023 series when in "PC Mode" (HDMI icon set to "PC") or enabling the new "4:4:4 Pass Through" toggle for leveraging 4:4:4 chroma, this at least for "non-Game" modes as SDR/HDR Filmmaker and DV Cinema presets.

The sequence would be:
1) Enable "PC Mode" on 2022 LG OLEDs or the new "4:4:4 Pass Through" toggle in 2023 LG OLEDs
2) Switch to SDR/HDR Filmmaker and DV Cinema presets
3) Enable Real Cinema first through ColorControl;
4) Then enable TruMotion "cinemaClear" / Cinematic Movement after.

I know that in the past this was not possible due to some limitation but is something changed now after latest ColorControl version?

Please, could you verify/test this and find/provide a workaround if this is still not possible yet?

Thank you,
-P

**Comment by Maassoft** [comment]
I don't think it's possible, but I can't say for sure because I don't have a 2022 or 2023 LG OLED.
If you'd really wanted to watch movies/series in PC mode, personally I'd just use a 120Hz signal so every frame would get displayed 5 times and there will be no judder. I don't think "Real Cinema" is needed then, unless you want to reduce the stuttering by introducing some motion interpolation.

**Comment by P40L0X** [comment]
> I don't think it's possible, but I can't say for sure because I don't have a 2022 or 2023 LG OLED. If you'd really wanted to watch movies/series in PC mode, personally I'd just use a 120Hz signal so every frame would get displayed 5 times and there will be no judder. I don't think "Real Cinema" is needed then, unless you want to reduce the stuttering by introducing some motion interpolation.

Mmmh, interesing.
I will try disabling the "Allow 24hz" option from Xbox Series X in order to let the console always stay with the 120hz signal, so that 24fps contents (as movies) will automatically use the 5:5 pulldown even without using the Real Cinema option.

I'll let you know if this works and how it looks as soon as my G3 will arrive.

Thanks :)

**Comment by P40L0X** [comment]
I will close this for now.
Thanks
