### ISSUE TITLE
v9.0.0.0 Does not Save LG Control Options

### ISSUE THREAD

**Issue by SimpleHeuristics** [Maassoft/ColorControl#197]
I installed v9 fresh to control my LG OLED, testing power off works when device is added as custom or auto detect but settings that are selected via the GUI checkboxes do not apply and do not persist past application restarts or PC restarts even when windows service is installed and app is set to start at login.

I cleared up v9 installation and used older v8.5, these settings would then work and when updated to v9 they would persist but once on V9 it was not possible to change these settings.

**Comment by GTMoraes** [comment]
I've already reported it a few days ago. Dev is aware.
