### ISSUE TITLE
Add option to hide the tray icon

### ISSUE THREAD

**Issue by aabdellah** [Maassoft/ColorControl#20]
An option to hide the tray icon and reopen the app from its icon would be very good.

**Comment by Maassoft** [comment]
I assume you want an option to disable the tray icon altogether and just use the task bar?

**Comment by aabdellah** [comment]
I'm thinking something like Nvidia control panel tray, you can disable it and still access it from it's start menu shortcut.

**Comment by Maassoft** [comment]
From version 2.1.0.0 you can now disable the system tray icon and if you start the program while it's already running it will simply open the main window of the running application.
