### ISSUE TITLE
Error opening Options Tab

### ISSUE THREAD

**Issue by Ojlkalfapf** [Maassoft/ColorControl#205]
I have this error opening options tab (see attached screenshot) on Windows 11 22H2 with NVIDIA 3070 gpu

<img width="1280" alt="Screenshot 2023-04-20 152142" src="https://user-images.githubusercontent.com/74552850/233379879-a21f290e-b6a4-4d4b-b6c5-8f522362fdeb.png">

**Comment by Maassoft** [comment]
Fixed with v9.1.1.0.
Did you maybe update your NVIDIA driver while the app was running? Normally this happens in such cases (or the driver was restarted by other reasons).

**Comment by Ojlkalfapf** [comment]
Hello
No, my mistake, I launched the program when dedicated gpu was inactive (I have a discrete graphic Intel-NVIDIA). Now all works flawlessy when NVIDIA graphic card is active. Thank you.

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows

Da: ***@***.***>
Inviato: venerdì 21 aprile 2023 20:16
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [Maassoft/ColorControl] Error opening Options Tab (Issue #205)


Fixed with v9.1.1.0.
Did you maybe update your NVIDIA driver while the app was running? Normally this happens in such cases (or the driver was restarted by other reasons).
