### ISSUE TITLE
Error while updating: a local file header is corrupt

### ISSUE THREAD

**Issue by av00va** [Maassoft/ColorControl#207]
![image](https://user-images.githubusercontent.com/16333281/233802280-cfdda82d-055b-4ddd-aeee-efdc6a5dfbb7.png)

Getting this error on bootup. Have it enabled as a service. I tried reinstalling; no luck.

**Comment by av00va** [comment]
To clarify, this happens every time an update is released. It won't update, but instead I have to copy and paste the files to the existing directory.

**Comment by Maassoft** [comment]
This is reported by another user as well (#204).
Can you check if there's a file "update.zip" in this folder:
`C:\Windows\System32\config\systemprofile\AppData\Roaming\Maassoft\ColorControl`
You probably need admin rights to view that folder.
If the file exists, can you manually extract it?

**Comment by Anthrobug** [comment]
I had the same problem - I couldn't extract the update.zip file, but if I copied it out and deleted the one inside that folder, then hit Update in the app, the process worked perfectly. I'm now updated - thank you!

**Comment by Maassoft** [comment]
Fixed with v9.2.0.0.

**Comment by av00va** [comment]
Thanks! Do you have a donate link?

**Comment by Maassoft** [comment]
No donate link yet, maybe in the future.
