### ISSUE TITLE
Process switch doesnt work in 9.1.1.0

### ISSUE THREAD

**Issue by vikdean** [Maassoft/ColorControl#209]
After updating to 9.1.1.0 none of the process switches work anymore which were working before. I've haven't changed anything.
Before it was visible in the logs when different settings were applied, but no longer.

TV: LG C2 - 03.30.67

**Comment by Amoeba00** [comment]
Did it work in v9.1.0 or just v8.x? 

FWIW, on my C1 - my process switch (I only have one to change the sound mode) still works after this update from both v8.x and v9.x.

**Comment by vikdean** [comment]
Well, the update from 9.0.0.0 to 9.1.0.0 then 9.1.1.0 was quite quick, so not sure. But it was definitely working in 9.0.0.0

**Comment by vikdean** [comment]
Got some logs finally, but its nothing conclusive:

> 2023-04-25 09:06:51.2807|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection with [LG] webOS TV OLED42C21LA...
> 2023-04-25 09:06:51.3192|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://192.168.1.62:3001
> 2023-04-25 09:06:53.0866|ERROR|ColorControl.Common.PipeUtils|PipeUtils.SendMessage|System.TimeoutException: The operation has timed out.
>    at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
>    at ColorControl.Common.PipeUtils.SendMessage(String message, Int32 timeout) in C:\Users\vinni\source\repos\ColorControl\ColorControl\Common\PipeUtils.cs:line 18
> 2023-04-25 09:06:53.1606|DEBUG|ColorControl.Services.LG.LgDevice|WOL succeeded
> 2023-04-25 09:06:56.2424|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C21LA] Power state change: {"state":"Active","subscribed":true,"returnValue":true}
> 2023-04-25 09:06:56.2424|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-25 09:06:56.2672|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C21LA] PictureSettingsChanged: {"brightness":"58","contrast":"80","color":50,"backlight":"24"}
> 2023-04-25 09:06:56.2765|DEBUG|ColorControl.Services.LG.LgDevice|Connect succeeded: True
> 2023-04-25 09:06:56.2765|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] webOS TV OLED42C21LA] ForegroundAppChanged: {"subscribed":true,"returnValue":true,"appId":"com.webos.app.hdmi1","processId":"","windowId":""}
> 2023-04-25 09:06:56.2928|DEBUG|ColorControl.Services.LG.LgService|Process monitor: test connection result: True
> 2023-04-25 09:06:56.2928|DEBUG|ColorControl.Services.LG.LgService|Process monitor: TV(s) where not connected, but connection has now been established
> 2023-04-26 01:01:07.3368|ERROR|ColorControl.Services.NVIDIA.NvGpuInfo|NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_ERROR
>    at NvAPIWrapper.Native.GPUApi.GetVFPCurveV3(PhysicalGPUHandle gpuHandle) in C:\Users\vinni\source\repos\ColorControl\NvAPIWrapper\Native\GPUApi.Performance.cs:line 429
>    at ColorControl.Services.NVIDIA.NvGpuInfo.ReadCurveV3() in C:\Users\vinni\source\repos\ColorControl\ColorControl\Services\NVIDIA\NvGpuInfo.cs:line 267
>    at NLog.Logger.Swallow[T](Func`1 func, T fallback)

**Comment by vikdean** [comment]
Yeah, seems to be working now. Thanks.
