### ISSUE TITLE
Request: Add the ability to add a TV to a command shortcut, so you can have per TV shortcuts. Also command line support.

### ISSUE THREAD

**Issue by xxTheGoDxx** [Maassoft/ColorControl#21]
So, I have a LG CX 48" as a monitor (pretty popular setup by now for owners of the 48" model) and a C9 65" in the living room, both connected to the same PC. I would like to use ColorControl to start macros on the active TV via a shortcut, but the TV controlled by ColorControl isn't switching automatically. The easiest solution for this would just to let the user choose the right TV for a shortcut. 

An command line argument option to start macros would be a further improvement over only having hotkeys. 

BTW, it took me some time wiggling around in Windows settings to find each TV. Could you also allow us to simply find the TV via the IP address? That would also allow PC's that are not connected to the TV via HDMI to be usable.

**Comment by Maassoft** [comment]
Thanks for your request. I will take it into consideration.
I will also look into command line support to start shortcuts. As a temporary workaround you could try using a AutoHotkey script which enables you to run arbitrary commands and also execute a keyboard shortcut to activate a preset in ColorControl.
BTW, I'm not sure the tv really needs to be connected via HDMI for it to be usable. I think Windows collects all UPnP devices that are connected on the same network and ColorControl just simply queries the device manager for specific devices.

**Comment by Maassoft** [comment]
I've added command line support in the latest release: 2.2.0.0.
Don't worry about your other requests, I'll try to add them in a next release.

**Comment by xxTheGoDxx** [comment]
Oh damn, I completely missed your other comment somehow. Thanks a lot for the tips, I indeed ended up using AHK (by the way tip: AHK also allows you to remap to F13 to F24 which many programs including yours support as hotkeys). 

And thanks for the update, this will simplify my setup a bit more. IMO your app is now a must have for everybody that uses their LG OLED with their PC (and is ok to invest some time setting stuff up).

**Comment by Maassoft** [comment]
With version 3.0.0.0 you can now add a tv to a preset. If you've had the time to test it, please report if it's working satisfactorily.
