### ISSUE TITLE
ColorControl still crashes on the background

### ISSUE THREAD

**Issue by GTMoraes** [Maassoft/ColorControl#214]
Hey,

ColorControl still seems to crash on the background, but it is a MUCH rarer occurrence than before (crashed twice so far in a couple of days, rather than hourly).

eventvwr logs are as follows:

Most recent error, from earlier today

> Faulting application name: ColorControl.exe, version: 9.1.1.0, time stamp: 0x63ed82c1
> Faulting module name: combase.dll, version: 10.0.22621.1485, time stamp: 0xa8be94cc
> Exception code: 0xc00000fd
> Fault offset: 0x0000000000105af7
> Faulting process id: 0x0xA030
> Faulting application start time: 0x0x1D97901059457A9
> Faulting application path: C:\GTMapps\ColorControl\ColorControl.exe
> Faulting module path: C:\WINDOWS\System32\combase.dll
> Report Id: 3a7f4468-a961-4e20-81bd-d4ec46c54ad2
> Faulting package full name: 
> Faulting package-relative application ID: 

This is the last data from the log at that time it crashed:

> 2023-04-27 09:11:19.8590|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-27 09:11:19.8590|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-27 09:11:19.9038|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-27 09:11:19.9038|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-27 09:11:19.9038|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-27 09:11:19.9038|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-27 09:12:04.1500|DEBUG|ColorControl.Forms.FormUtils|Detected NotificationState change from QUNS_ACCEPTS_NOTIFICATIONS to QUNS_NOT_PRESENT
> 2023-04-27 09:12:04.6103|DEBUG|ColorControl.Services.LG.LgService|Screensaver started: Mystify.scr, parent: winlogon
> 2023-04-27 09:12:04.6103|DEBUG|ColorControl.Services.LG.LgService|Screensaver check: test connection with [LG] GT TV 65...
> 2023-04-27 09:12:04.6103|DEBUG|LgTv.LgTvApi|Trying to connect with websocket uri: wss://10.0.0.154:3001

IIRC it's exactly like before

The other time it crashed, on eventvwr:

> Faulting application name: ColorControl.exe, version: 9.1.1.0, time stamp: 0x63ed82c1
> Faulting module name: combase.dll, version: 10.0.22621.1485, time stamp: 0xa8be94cc
> Exception code: 0xc00000fd
> Fault offset: 0x0000000000105af7
> Faulting process id: 0x0x1358
> Faulting application start time: 0x0x1D976F642357DC9
> Faulting application path: C:\GTMapps\ColorControl\ColorControl.exe
> Faulting module path: C:\WINDOWS\System32\combase.dll
> Report Id: abfda563-abd3-4bb4-9bfe-b9cdab4b6bd9
> Faulting package full name: 
> Faulting package-relative application ID: 

In comparison, these were the 9.1.0.0 errors:

> Faulting application name: ColorControl.exe, version: 9.1.0.0, time stamp: 0x63ed82c1
> Faulting module name: combase.dll, version: 10.0.22621.1485, time stamp: 0xa8be94cc
> Exception code: 0xc00000fd
> Fault offset: 0x0000000000105af7
> Faulting process id: 0x0x6BE4
> Faulting application start time: 0x0x1D9745CE871A63A
> Faulting application path: C:\GTMapps\ColorControl\ColorControl.exe
> Faulting module path: C:\WINDOWS\System32\combase.dll
> Report Id: 8f22eef0-4d52-4955-8a90-819af444fc0a
> Faulting package full name: 
> Faulting package-relative application ID: 

Looks like the same exception and offset.

Some things to note:

- I don't turn off this PC, like ever. It, at most, reboots when it MUST do so, as in for Windows updates or if something is too wonky.

- Looking at the ColorControl logs, it seems to throw a couple (22 occurrences in a 44k lines log file) of "Inner Exception" errors, such as:

> Inner exception: 0x80072EE2
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at LgTv.LgTvApiCore.Connection_MessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args) in C:\Users\vinni\source\repos\ColorControl\ColorControl\LgTv\LgTvConnection.cs:line 242

- Also, I'm not sure if that's normal, but...

> 2023-04-26 13:04:34.4508|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:04:34.4508|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:04:34.4882|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:04:34.4882|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:04:34.4882|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:04:34.4882|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:06:44.4557|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:06:44.4557|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:06:44.4814|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:06:44.4814|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:06:44.4814|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:06:44.4814|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:08:54.4441|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:08:54.4441|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:08:54.4940|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:08:54.4940|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:08:54.5066|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:08:54.5066|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:11:04.4522|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:11:04.4522|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:11:04.4838|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:11:04.4838|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:11:04.4838|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:11:04.4838|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:13:14.4686|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:13:14.4686|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:13:14.5155|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:13:14.5155|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:13:14.5174|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:13:14.5174|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:15:24.4515|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:15:24.4515|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:15:24.4911|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:15:24.4911|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:15:24.4911|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:15:24.4911|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:17:34.4957|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:17:34.4957|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:17:34.5134|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:17:34.5134|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:17:34.5188|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:17:34.5188|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:19:44.4499|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:19:44.4499|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:19:44.4887|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:19:44.4887|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:19:44.4887|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:19:44.4887|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:21:54.4693|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:21:54.4693|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:21:54.4778|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:21:54.4778|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:21:54.4778|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:21:54.4778|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:24:04.4458|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:24:04.4458|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:24:04.5022|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:24:04.5022|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:24:04.5022|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:24:04.5022|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:26:14.4641|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:26:14.4641|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:26:14.5066|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:26:14.5066|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:26:14.5066|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:26:14.5066|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:28:24.4506|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:28:24.4506|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:28:24.4938|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:28:24.4938|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:28:24.4938|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:28:24.4938|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:30:34.4441|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:30:34.4441|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:30:34.4717|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:30:34.4717|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:30:34.4717|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:30:34.4717|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:32:44.4504|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:32:44.4504|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:32:44.4927|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:32:44.4927|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:32:44.4927|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:32:44.4927|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:34:54.4440|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:34:54.4440|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:34:54.4755|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:34:54.4755|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:34:54.4905|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:34:54.4905|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:37:04.4421|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:37:04.4421|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:37:04.4855|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:37:04.4855|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:37:04.4873|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:37:04.4873|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:39:14.4729|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:39:14.4729|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:39:14.4729|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:39:14.4729|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:39:14.4729|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:39:14.4729|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:41:24.4459|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:41:24.4459|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:41:24.4766|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}
> 2023-04-26 13:41:24.4766|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:41:24.4766|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active"}
> 2023-04-26 13:41:24.4766|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:43:34.4491|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Request Screen Saver"}
> 2023-04-26 13:43:34.4491|DEBUG|ColorControl.Services.LG.LgDevice|PoweredOffBy: Unknown, PoweredOffViaApp: False
> 2023-04-26 13:43:34.4948|DEBUG|ColorControl.Services.LG.LgDevice|[[LG] GT TV 65] Power state change: {"returnValue":true,"state":"Active","processing":"Screen On"}

This is an excerpt from the log file. It has over 44,000 lines. There are thousands of lines like that.
Is that correct or is it too verbose for some reason?

Btw, thanks for fixing all issues I've reported so far! This app is great!

**Comment by lahma0** [comment]
I'm definitely still experiencing these same crashes as well. However, I certainly wouldn't call them "infrequent". Seems like every time I leave my computer for an extended period of time, whenever I come back the ColorControl.exe process has quietly crashed/stopped.

**Comment by Maassoft** [comment]
Yes, happened to me a couple of times as well. But it should be fixed now with v9.2.0.0. Haven't had the crashes again while testing it.

**Comment by GTMoraes** [comment]
Gonna give it a shot!

Also,

> Perform action even on manually executed screen saver: normally only the screen saver that is initiated by Windows is used as a trigger, but with this option engaged a manually started screen saver is valid as well

Ha, that's amazing. I was thinking of setting up a button on my kb to turn the screensaver ON, for moments where it wouldn't come up (like when a game is playing on the background or if there's some other piece of software preventing the screensaver to come up), but ColorControl wasn't turning the TV off in these scenarios.
You read my mind and added it lol 

Thank you once again!

**Comment by GTMoraes** [comment]
Looking good so far. Closing this! Thank you.
