### ISSUE TITLE
NVIDIA controller tab missing after 9.0.0.0 and upwards

### ISSUE THREAD

**Issue by Acaki** [Maassoft/ColorControl#219]
[LogFile.txt](https://github.com/Maassoft/ColorControl/files/11366386/LogFile.txt)

I tried to delete the settings folder AppData\Roaming\Maassoft\ColorControl and let it generate new one but the same error still occurs

I also tried to tick/untick NVIDIA tab in the options but it makes no differences

The last working version for me was 8.5.0.0

**Comment by Maassoft** [comment]
Your log indicates that the text for the notify icon (system tray) is too long, probably because you have 3 displays. I see that the limit is 127 chars and I have removed the code that was truncating the text in earlier versions. I will fix this in the next release.

**Comment by Acaki** [comment]
Hey I confirmed 9.3.0.0 fixed my issue, thanks a lot
