### ISSUE TITLE
Idea - power off screen after idle time

### ISSUE THREAD

**Issue by majoracehole** [Maassoft/ColorControl#22]
Great app - love it!

I wondered if this would be useful to anyone other than me, and hopefully makes sense -
Windows normally turns the display "off" after a few minutes idling, and on many monitors, being without input triggers a standby mode, but the LG oleds stay switched on with the "no signal message"

So adding an option for an idle timer in the app to switch off the oled after however long, and on again on any keyboard/mouse activity - would be handy! (rendering the windows power settings irrelevant)

(previously the power off/on when PC standby options would have been perfect, but these days I tend to leave my PC on and mining when away)

**Comment by Maassoft** [comment]
Thanks for appreciating my app!
Coincidentally I've had sort of the same idea lately. I most of the time use a shortcut to activate the blank screen saver whenever I'm away for a couple of minutes from the screen, but for a longer period automatically powering off the tv would be better.
I think it is possible to detect whenever the Windows screensaver (or power "off") activates and then to power off the tv right at that moment.

**Comment by Maassoft** [comment]
I've incorporated this functionality in the new release 2.1.0.0. Feel free to test it.

**Comment by majoracehole** [comment]
Great! Seems to work pretty well :) my main beef is now getting windows to start up the screensavers reliably!

**Comment by Maassoft** [comment]
Thanks for testing. Yes, the screensaver sometimes may have issues depending on what programs are active at the time. I've noticed this as well when MS Teams is active for example.
But my app has still some issues as well I need to fix. If you manually turn off the tv it may automatically turn on again if you enable this feature. That's not really what you would expect. Will be fixed in the next release.

**Comment by MahmoudAlyuDeen** [comment]
@majoracehole if you find a way to do that, please let me know. It's very frustrating to fall asleep and wake up finding my media player still on the TV burning away at my hard-earned pixels.

**Comment by majoracehole** [comment]
If you're referring to Windows Media Player specifically, there is an option in its settings that prevents the screensaver loading up!

While its not perfect - to be fair to Windows as of late I've not noticed many (if any) times the screensaver didn't load
