### ISSUE TITLE
Changing Picture Actions Hangs on Menu LG C2

### ISSUE THREAD

**Issue by BoredErica** [Maassoft/ColorControl#226]
I have LG C2 42in. I want to change pixel brightness (backlight option) but when I try to, it just opens the menu and hangs. For example, "backlight(18), EXIT" just opens the menu and it never closes or change backlight. No error message from Color Control. It's as if it opens menu, sees backlight command, and cancels the entire preset so it never gets to exit the menu.

This applies to Brightness/Black Level and picture mode settings as well. It works fine for turning the TV off. 

Strangely, backlight level changing was fine a few hours ago and worked for 2 days but now it just stopped working for some reason.

I've tried to install ColorControl on my extra laptop and run backlight level change and there is the same issue. This suggests to me the issue is either with the TV or me applying settings incorrectly twice on two different computers. TV is on 3.30.67.

Thanks.
[Screenshot](https://github.com/Maassoft/ColorControl/assets/52505513/0d3d9d0e-cd3c-4bd2-8750-aa758b7ef521)

**Comment by Maassoft** [comment]
This might be caused by the App "Settings" that is selected. When changing settings directly (like "backlight(xx)") the Settings app doesn't need to be opened. You can clear the App by selecting the drop down and pressing backspace.
If it still doesn't work, try changing some settings via the Expert-button. If that was working before, maybe the firmware was updated and LG blocks this method now 🤔

**Comment by BoredErica** [comment]
> This might be caused by the App "Settings" that is selected. When changing settings directly (like "backlight(xx)") the Settings app doesn't need to be opened. You can clear the App by selecting the drop down and pressing backspace. If it still doesn't work, try changing some settings via the Expert-button. If that was working before, maybe the firmware was updated and LG blocks this method now 🤔

Thanks for the reply. I updated firmware and that somehow fixed it, which is weird because I hadn't updated the firmware ever before that and it stopped working out of the blue. In future I will try your tip to not include settings app. :)

There's no easy way to both change brightness w/ ColorControl hotkey and switch to correct icc profile for the correct brightness, right? Trying to think how I'd code such a thing in AHK.
