### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ledoge** [Maassoft/ColorControl#231]
See my comment [here](https://github.com/Maassoft/ColorControl/issues/222#issuecomment-1561517951)

**Comment by Maassoft** [comment]
Thanks for your comment. I've added the necessary licenses to the source.
Can you check if the "LICENSE_NOVIDEO.txt" provides sufficient information? Most of your code is unchanged, I've only removed the dithering settings to avoid confusion with the other dithering settings already included in ColorControl.

Btw, talking about dithering, I'm currently testing a new Samsung TV (S95C), but for some reason dithering has only effect on the left half of the screen. Now this TV seems to use HDMI 2.1 DSC and maybe the GPU drives it as 2 "virtual" displays. But using the NvAPI I'm only seeing 1 display, thus only 1 displayId to specify via the SetDitherControl function. I don't think you know how to properly set dithering in this case? I think it might probably be just the NvAPI that's not supporting this situation, or there's another hidden function.

**Comment by ledoge** [comment]
>Can you check if the "LICENSE_NOVIDEO.txt" provides sufficient information?

Looks good, thank you. Please also make sure to include the license files in future binary releases.

>maybe the GPU drives it as 2 "virtual" displays

AFAIK this is pretty much how it works, due to limitations of NVIDIA's display engine. Not sure about the internal workings, but on some level it takes up two outputs. I assume that dithering therefore needs to be done on both outputs, and if the API only sets the parameters on one of them, that seems like a bug in the driver.

Not really sure what you could try, other than filing a bug report with NVIDIA. I assume rebooting doesn't fix it?

Also, how exactly does the right half of the display behave? Does it follow the default setting of not dithering e.g. in 8 bit full range SDR, but performing dithering e.g. in limited range output or 8 bit HDR?

**Comment by Maassoft** [comment]
Thanks for the response.

The right half of the display follows the default dithering behavior: disabled in SDR, but 8-bit temporal dithering in HDR when using "default color settings". Rebooting doesn't seem to fix it. But it only seems to act weirdly when using the highest refresh rate of 144Hz. Probably a bandwidth issue which requires the display to operate in a special mode, I don't know...
