### ISSUE TITLE
Log file bloat causes program hang/crash

### ISSUE THREAD

**Issue by Amoeba00** [Maassoft/ColorControl#234]
Noticed that with this latest version the log file is growing significantly (10MB+) and as a result the program will hang if you click on the log file tab.  The fix is to delete the log file outside of CC, but I was wondering if there was a setting to reduce verbosity or to be able to set a max size?

Thanks!

**Comment by Maassoft** [comment]
Currently it is not possible to reduce verbosity or to set a max size. I will add these to a next release.

**Comment by Amoeba00** [comment]
This doesn't seem to be an issue with the latest version (v9.6.4) - log file sizes are very manageable now.
