### ISSUE TITLE
LG C8 firmware downgrade not working

### ISSUE THREAD

**Issue by cg8440** [Maassoft/ColorControl#237]
I am using the latest version of ColorControl (9.5.0.0). Recently, I I tried to downgrade the firmware on my LG C8 (currently version 5.50.15). When sending the command through ColorControl>Expert>software update, I see a screen on my tv identifying the current firmware version on the tv, and the new firmware version on the USB stick. When I click update on my TV, it shows a message, “This firmware cannot be installed, closing the app now.”

Did LG takeaway the ability to install/downgrade firmware through ColorControl? I remember I successfully did this more than a year ago, when I was using ColorControl Version 4.0.0.0. 

Any other options to change firmware now??

By the way, thanks to the developers of this app, for at least having a reboot option in the app, so that we can reboot the WebOS on the tv.

**Comment by Maassoft** [comment]
I'm afraid LG blocked downgrading the firmware a while ago, with a firmware update around the end of 2021 or beginning of 2022. So as far as I know, if you have the latest installed there's nothing you can do anymore.
