### ISSUE TITLE
LG Controller wont detect LG 48cx anymore

### ISSUE THREAD

**Issue by JeffLoDavao** [Maassoft/ColorControl#24]
![image](https://user-images.githubusercontent.com/81326154/113469885-b9935800-9483-11eb-8356-cb17d51501cd.png)

hello the LG controller wont detect the TV ip add anymore, is thier a way to manually add the ip address of the tv?

**Comment by JeffLoDavao** [comment]
192.168.50.249 and .230 are the old ip add the tv use but now ive change to 192.168.50.20 but colorcontrol see it as still with the old ip add

**Comment by JeffLoDavao** [comment]
or is thier a way to uninstall it and start new?

**Comment by Maassoft** [comment]
ColorControl uses Windows device manager to search for your tv's. You can try deleting the tv under Digital Media Devices and Software devices and then use the option "Scan for new hardware".
![image](https://user-images.githubusercontent.com/70057942/113474064-c7d67980-946d-11eb-9d8d-0a28d27d2c88.png)

If the tv reappears, restart ColorControl and hopefully it will detect the new ip addresses.
In a new version I will add manual adding of ip/MAC addresses.

**Comment by Maassoft** [comment]
Version 3.0.0.0 allows manually adding devices, so I'll close this issue.
