### ISSUE TITLE
9.6.1.0 throws errors anytime LG Controller is accessed

### ISSUE THREAD

**Issue by Areteic** [Maassoft/ColorControl#242]
Hello there,
Unable to do anything in LG Controller since clicking on it and on anything in it throws error as seen in the screenshot.
![Screenshot 2023-06-28 171550](https://github.com/Maassoft/ColorControl/assets/1826961/5dbf1252-fc30-4290-beae-3ea219dcbada)

Tried full uninstall and reinstall but did not achieve anything. Returned to 9.6.0.0, no such error messages there.
Thanks!

**Comment by Maassoft** [comment]
I've just released 9.6.1.1 to fix this issue. Please check if it works.

**Comment by Areteic** [comment]
Thanks, that fixed it!
