### ISSUE TITLE
ColorControl simply stopped working in 9.6.1.0

### ISSUE THREAD

**Issue by ProBlade97** [Maassoft/ColorControl#243]
![image](https://github.com/Maassoft/ColorControl/assets/34210533/4ec27672-7e9c-48c9-a8be-e38e640d5bdf)

I'm in the LG Controller tab it keeps popping this when i click on anything in this tab. To the point where i can't even change the tab.

**Comment by Poet611** [comment]
Hi. I have the same error when I launch the app. It's also happening with the new version 9.6.1.1

**Comment by Maassoft** [comment]
That's weird, it should be fixed with 9.6.1.1. Did you update manually or did it automatically install the update?

**Comment by ProBlade97** [comment]
works when i updated. thanks.
