### ISSUE TITLE
disable screensaver

### ISSUE THREAD

**Issue by danhausman** [Maassoft/ColorControl#245]
Is there a button for disable screensaver?  I have an LG LED tv, and I don't see any options anywhere in the service menu to change the timing or disable it.   I know I will have burn in and reduce the life of the tv, I am trying to use it as a display board.

**Comment by Maassoft** [comment]
I don't know. Is it the screensaver that starts after 2 minutes while using internal apps? If you use HDMI inputs the internal screensaver normally doesn't start. Maybe sending remote control buttons (like BACK) periodically via ColorControl (or other means) will prevent starting the screensaver.

**Comment by danhausman** [comment]
I was using the app specifically the web browser. The screen saver kicks in at about 45 minutes.

**Comment by danhausman** [comment]
I had a cray thought, would it be possible to send a remote command like the OK button over the network using something like curl?   I could create a cron job on my raspberry pi to send it every so often.  That should keep it awake right?

**Comment by Maassoft** [comment]
Yes, that should work. There are several Node.js libraries for LG TV's (initially I've used it in ColorControl) which let you connect to the TV via web sockets and once it's connected you can send remote control commands to your liking.
There are also some Python projects which do the same (like https://github.com/chros73/bscpylgtv) and I think those should work on a Raspberry Pi.

**Comment by danhausman** [comment]
I tried bscpylgtv and it worked perfectly to keep my screen alive.  Thanks for your help!
