### ISSUE TITLE
Cannot disable Samsung module

### ISSUE THREAD

**Issue by jesstech** [Maassoft/ColorControl#247]
ColorControl 9.6.2.0 installed with elevated Windows service

I do not have a Samsung TV, nor do I want to control one.  

### Steps to reproduce: 
1. Uncheck "Samsung Controller" from the 'Modules' fieldset under Options
2. Restart ColorControl

### Expected behavior:
"Samsung controller" disappears from systray icon context menu and main application tabs.  All network communication for Samsung devices ceases.

### Actual Behavior:
"Samsung controller" remains in systray icon context menu and main application tabs.  "Samsung controller" checkbox is re-checked in the 'Modules' fieldset under Options.

**Comment by Maassoft** [comment]
Thanks for the report. I will look into it.

**Comment by Maassoft** [comment]
Was already fixed with v9.6.3.0.
