### ISSUE TITLE
Add option to name Nvidia presets

### ISSUE THREAD

**Issue by laxu** [Maassoft/ColorControl#25]
Now the preset lists just lists the various modes which all kind of blend together and need to be carefully looked through.

If I could have for example presets named "120 Hz HDR" or "120 Hz SDR" then those would be faster to find. The functionality could be "show preset name, if empty show format".

**Comment by Maassoft** [comment]
Thanks for the suggestion. I think it's a good idea, because I need those names as well for the command line issue that was added recently. Then you can execute presets from the command line, regardless of ColorControl is already opened or not.

**Comment by Maassoft** [comment]
I've added this in the new release 2.2.0.0.

**Comment by laxu** [comment]
Seems to work great!
