### ISSUE TITLE
need macOS version

### ISSUE THREAD

**Issue by n-WN** [Maassoft/ColorControl#250]
Need remote control page and configure LG C1 automatic switch function

**Comment by Maassoft** [comment]
Unfortunately I don't have a Mac and ColorControl is currently highly dependent on Windows, so this won't be implemented in the foreseeable future.
In the mean time you could use some other projects that will probably work on Mac, like [bscpylgtv](https://github.com/chros73/bscpylgtv). With this you can execute a lot of commands and it shouldn't be that difficult to make an UI for this.

**Comment by n-WN** [comment]
> Unfortunately I don't have a Mac and ColorControl is currently highly dependent on Windows, so this won't be implemented in the foreseeable future.
> 不幸的是，我没有Mac，ColorControl目前高度依赖Windows，因此在可预见的未来不会实现。
> In the mean time you could use some other projects that will probably work on Mac, like [bscpylgtv](https://github.com/chros73/bscpylgtv). With this you can execute a lot of commands and it shouldn't be that difficult to make an UI for this.
> 同时，您可以使用其他一些可能在Mac上运行的项目，例如bscpylgtv。有了这个，您可以执行很多命令，为此制作 UI 应该并不难。

thk You
