### ISSUE TITLE
Question:  Direct access to input icon setting? (Model: C1)

### ISSUE THREAD

**Issue by Amoeba00** [Maassoft/ColorControl#262]
Is there a quicker way to trigger the input selector on the Home Dashboard to change from HDMI to PC other than the step-by-step?  Under the "Other" menu option - there is one called "HdmiPcMode_hdmi#" - then "enable/disable" - but I can't get that to work on my C1.  Is that option model specific?

![image](https://github.com/Maassoft/ColorControl/assets/39176113/65332ee5-a286-41d8-abb5-d4617cd5a0c1)

Meanwhile - I have been able to create the following custom triggers which is certainly better than doing it with the remote:
Change HDMI 1 to PC Mode:
UP:1500, UP:500, UP:500, RIGHT:500, ENTER:1000, ENTER:1000, ENTER:1000, DOWN:500, LEFT:500, ENTER:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, ENTER:500, UP:500, RIGHT:500, ENTER:500, RIGHT:500, RIGHT:500, ENTER

Change HDMI 2 to PC Mode:
UP:1500, UP:500, UP:500, RIGHT:500, ENTER:1000, ENTER:1000, ENTER:1000, DOWN:500, DOWN:500, LEFT:500, ENTER:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, ENTER:500, UP:500, UP:500, RIGHT:500, ENTER:500, RIGHT:500, RIGHT:500, ENTER

Thanks!

**Comment by Maassoft** [comment]
The "HdmiPcMode_hdmi#" settings only work on older models (C8, C9 and maybe CX).
But there is a setting to directly change the "icon" of the HDMI port. You can do this under Misc -> HDMI # icon.

**Comment by Amoeba00** [comment]
Exactly what I was looking for - genius!  thanks again!
