### ISSUE TITLE
Please, help. After I pulled out and inserted the processor, I began to receive this error

### ISSUE THREAD

**Issue by pioklo** [Maassoft/ColorControl#27]
Please, help. After I pulled out and inserted the processor, I began to receive this error
https://prnt.sc/12u7e7n
How to fix it?

**Comment by Maassoft** [comment]
I think that the config files are corrupted. You can find and delete them in this folder:
C:\Users\<username>\AppData\Roaming\Maassoft\ColorControl

I would start with deleting the LgConfig.cfg and try if the app starts then.
I've encountered this issue before after Windows crashed.

**Comment by pioklo** [comment]
Thank you. I have already fixed this issue as you said.
