### ISSUE TITLE
[feature request] Add G-Sync to the nVidia settings

### ISSUE THREAD

**Issue by MahmoudAlyuDeen** [Maassoft/ColorControl#28]
Hi, can you maybe add the option under Nvidia Controller to turn gsync on and off?

**Comment by Maassoft** [comment]
Unfortunately the [NvAPIWrapper](https://github.com/falahati/NvAPIWrapper) I'm using does not support G-Sync yet. I could set up the delegates manually like I do with some other calls, but that requires some research. Therefore it could take some time before this is added.
