### ISSUE TITLE
Would it be possible to unlock the hidden/simplified menu on the LG B3 in the same manner as the C3/G3?

### ISSUE THREAD

**Issue by DKonneker** [Maassoft/ColorControl#282]
I was hopeful that I could use the same feature to unlock the simplified menu on the B3 the same way as what has been demonstrated on the LG C3/G3 but I think that feature in the ColorControl software only appears once the software detects the corresponding model.  Would it be possible to unlock the hidden/simplified menu on the LG B3 in the same manner as the C3/G3?

**Comment by Maassoft** [comment]
I've just released v9.7.1.0 which now also unlocks this for the B3.

**Comment by DKonneker** [comment]
I just tested it and it works perfectly on my LG B3 (with the original firmware from the factory).  Thank you.
