### ISSUE TITLE
It stopped working on LG C2 after the last firmware update to version 03.33.90

### ISSUE THREAD

**Issue by Ianproquo** [Maassoft/ColorControl#286]
It stopped working completely after the update

**Comment by Amoeba00** [comment]
Do you know what was your firmware version beforehand when it did work?  Also, do you have that "Use secure connection" option enabled?

**Comment by Ianproquo** [comment]
Last version was 03.33.85. "Use secure connection" option enabled.

**Comment by Amoeba00** [comment]
Have you confirmed that the IP address hasn't changed? 
 Do you see "Hello world" when you point your computer browser to https://TV.IP:3001 ?
Can you elaborate what "completely stopped working means"  Which version of CC are you using?

**Comment by Ianproquo** [comment]
I'm not sure has it changed but they are in the same subnet: TV IP is 192.168.21.142 and PC IP is 192.168.21.140.
I don't see "Hello world" by typing https://192.168.21.142:3001/ at my web browser.
I'm using ColorControl 9.7.1.0 version.
By stopped working I mean whatever I do TV does not react and ColorControl shows me "Error executing action: Not connected"

**Comment by Amoeba00** [comment]
Glad you got it working! (but I'm not the developer -  just a fellow end user who has run into many of these issues before and knows the frustration when stuff doesn't work).  Meanwhile, go ahead and close the ticket and have a great day!

**Comment by Ianproquo** [comment]
Thank you for you help! 😊
