### ISSUE TITLE
Unable to get nVidia controller and Game controller presets to show up in Quick Access.

### ISSUE THREAD

**Issue by Jason-GitH** [Maassoft/ColorControl#290]
I have checked the "Show in Quick Access" box next to several nVidia and Game controller presets but they won't show up. The LG controller presets do show, however.

![image](https://github.com/Maassoft/ColorControl/assets/101422827/cf805b97-e19e-4318-8389-ad573da25df9)

**Comment by Maassoft** [comment]
Like I mentioned in the other issue, every tab has its own "Quick Access" with a different shortcut. You can configure the shortcut via the Settings->Settings button.
