### ISSUE TITLE
Edge Web View on the Info tab should be loaded lazily

### ISSUE THREAD

**Issue by marcinsmialek** [Maassoft/ColorControl#294]
ColorControl creates msedgewebview2.exe instances even when it's auto started to tray.

This consumes resources, despite being rarely used.
Lazy loading on tab change should do the trick.

I don't think that unloading is critical.

**Comment by Maassoft** [comment]
Thanks for noticing! I've implemented lazy loading and now the msedgewebview2.exe processes only appear after visiting the Info tab page. Will be fixed in the next release.

**Comment by Maassoft** [comment]
Fixed with v9.7.2.0 or higher.
