### ISSUE TITLE
Exception when trying to send LG controls after restarting TV

### ISSUE THREAD

**Issue by mirkendargen** [Maassoft/ColorControl#3]
If I leave the application running, turn off the TV for some time, turn it on again, and then attempt to send controls to the TV, the application throws an unhandled exception every time. If I close the program and reopen it, it once again works.

**Comment by mirkendargen** [comment]
Exception text:

************** Exception Text **************
System.ObjectDisposedException: The object has been closed. (Exception from HRESULT: 0x80000013)
   at Windows.Storage.Streams.DataWriter.StoreAsync()
   at LgTv.LgTvApiCore.<SendMessageAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by Maassoft** [comment]
I was able to reproduce the problem. In my case the entire application even closed after the exception. I will make the app more robust by letting it detect a disconnect better and reconnect when necessary.

**Comment by Maassoft** [comment]
Should be fixed in 1.2.0.0. Please test if possible. It could be that there will still be an error logged on the Info-tab, but the app should automatically reconnect now.

**Comment by mirkendargen** [comment]
I tested and verified it's working now!
