### ISSUE TITLE
WebOS23. No access to full service menu on OLED A2.

### ISSUE THREAD

**Issue by AndreyArbaiten** [Maassoft/ColorControl#304]
Good day. Also, after updating to WebOS23, on 2022 models such as OLED48A2 there is no access to the full service menu. Could you please add support for A2.

**Comment by AndreyArbaiten** [comment]
Software version 13.30.21 WebOS23. 8.2.0-16(number1-nambung)

**Comment by Maassoft** [comment]
A2 and A3 models are now supported with v9.8.0.1.
