### ISSUE TITLE
Json Error

### ISSUE THREAD

**Issue by sagman76** [Maassoft/ColorControl#32]
Hi, 
I keep getting the below error after Windows update. I have deleted downloaded the newest version but same issue. Any help would be appreciated
Thanks
![Capture](https://user-images.githubusercontent.com/85863612/121847965-473fbf00-cce1-11eb-9c21-d771960a365a.PNG)

**Comment by Maassoft** [comment]
I think one of the Json configuration files might be corrupted. You can find these here:
C:\Users\<username>\AppData\Roaming\Maassoft\ColorControl

It probably is the "Settings.json". Just delete it and it will regenerate.
