### ISSUE TITLE
WOL (and Power button command) cause a spinning circle to appear on LG CX TV

### ISSUE THREAD

**Issue by Lamda604** [Maassoft/ColorControl#322]
Hi, I have been using ColorControl for quite some time with this TV. Recently after updating to the latest version of ColorControl I wasn't able to connect to the TV and kept getting pop up errors. I tried to troubleshoot as much as possible but finally found the link to uninstall the program and reinstalled it clean.

I've since been able to connect to the tv but I'm noticing that using WOL command in a preset causes the tv to turn on but then display a slow spinning circle on the lower portion of the screen that won't go away unless I hit a menu or settings screen button. When I created a preset that turns off the tv with a hot key using the POWER command it also generates the spinning circle before the TV turns off.

When I use the Test power on/off option in the Settings menu, I do NOT see the spinning circle at all when using it to turn the tv off or back on.

Using commands like HDMI1 do not cause the spinning circle either.

As a temporary workaround I've added the HOME command twice after the WOL command to make these spinning circle go away.

Have you seen this issue before?

Also is there a way to access the ColorControl service on and off function? Or just use WOL and POWER?

Thanks!

[LogFile.txt](https://github.com/Maassoft/ColorControl/files/14366675/LogFile.txt)
![pic](https://github.com/Maassoft/ColorControl/assets/81937940/6c28b7b9-9ead-4dce-b2ac-49352fb7a52d)

**Comment by Maassoft** [comment]
According to your screenshot, it seems you have an app configured in the TV On/Off presets: com.webos.app.dangbei-overlay.
So after powering on it will directly try to launch that app. You can remove the app by pressing Backspace while the App-drop down is focused.

**Comment by Lamda604** [comment]
got it, thank you
