### ISSUE TITLE
LG controller disappeared. How to reset program?

### ISSUE THREAD

**Issue by Jason-GitH** [Maassoft/ColorControl#324]
The LG Controller tab has disappeared. I think this had something to do with setting my Quick Access shortcuts because when I set them, I received an error message. I have deleted the program folder & downloaded program again. I also deleted the LG config files from App Data folder, but the tab is still missing.

Nvm: I figured out how to restore it by deleting the entire Maasoft folder under App Data.

**Comment by zmz125000** [comment]
Uninstall windows service, exit the program, find and delete all colorcontrol folder using everything search, start the program. That should reset all colorcontrol settings.
