### ISSUE TITLE
HDR gamma profile: What value should I use for Windows SDR content brightness?

### ISSUE THREAD

**Issue by zmz125000** [Maassoft/ColorControl#326]
dylanraga provided a table of values to set the Windows SDR content brightness corresponded to different icm profile. 

When using color control to generate the profile, What value should I use for Windows SDR content brightness?

Thank you.
![image](https://github.com/Maassoft/ColorControl/assets/11844731/1d1c8ed7-f6e8-4e8f-8d64-bf3dbd44ee67)
![image](https://github.com/Maassoft/ColorControl/assets/11844731/f1efbdef-af75-444a-80ca-0b5acc80a477)
![image](https://github.com/Maassoft/ColorControl/assets/11844731/8f9e596e-a3ed-4232-8bed-b6d64d299c94)

**Comment by Maassoft** [comment]
You should use the "nits" value of the provided table (SDR white screen luminance) and put it in the "SDR maximum brightness (nits)" field in Color Control. Default this is 100 nits which corresponds with the Windows SDR slider at 5%.

**Comment by zmz125000** [comment]
Tried 200 nits with gamma 2.2 and 300 nits with gamma 2.4, the results are very impressive on LG C2. SDR brightness now on part with miniLED TV with a much better picture quality.
