### ISSUE TITLE
OLED Motion Pro flickering on C9 TV.

### ISSUE THREAD

**Issue by z826540272** [Maassoft/ColorControl#33]
anybody has this issue?
when i enable motion pro ,screen get flickering crazy.after a few seconds, the TV get auto shutdown.
same behavier when I switch to a CX mainboard with Motion pro enable.

**Comment by Maassoft** [comment]
I've read there were more users having this problem, check this out: https://www.avsforum.com/threads/2019-lg-c9-e9-oled-motion-pro-feature.3192676/

No issues on my tv fortunately...

But I'm closing this issue, it is not related to this app.
