### ISSUE TITLE
Several UI elements are scaling incorrectly

### ISSUE THREAD

**Issue by wrhight** [Maassoft/ColorControl#332]
Several UI elements are having trouble showing up correctly in the window. Looks like there are some scaling issues.

<img width="1191" alt="Screenshot 2024-03-11 120728" src="https://github.com/Maassoft/ColorControl/assets/16967707/63cd1a22-9a17-4224-bee7-d2c556c2812d">
<img width="801" alt="Screenshot 2024-03-11 120739" src="https://github.com/Maassoft/ColorControl/assets/16967707/636d0a1a-b2a3-426f-a10f-2b2cc79ceefb">
<img width="796" alt="Screenshot 2024-03-11 120755" src="https://github.com/Maassoft/ColorControl/assets/16967707/1c86288f-4ae1-40ab-b19f-88de417c29a2">

Changing the window size only helps slightly, as you can see sometimes it causes elements to outright disappear.

**Comment by 07Repsol** [comment]
Same here, using Win10 250% scaling on my C2.

**Comment by Maassoft** [comment]
Fixed with 9.8.2.1 or higher.
