### ISSUE TITLE
minimized setting is not saved

### ISSUE THREAD

**Issue by NeverBeLazyG** [Maassoft/ColorControl#336]
hi,

thh "start minimized" is not saved. it always unticked after start.

![Screenshot 2024-03-18 120224](https://github.com/Maassoft/ColorControl/assets/98562993/b15c9e67-4569-4f2c-b17f-19942f9eb044)

**Comment by 07Repsol** [comment]
Me too. Weird thing is I got no problem after updating to 9.8.2.1. Yesterday I reinstalled Win10, then the setting can't be saved.

**Comment by eL3cTr1c4L** [comment]
I can also confirm the issue, just y`day installed an el nuvo Windoz 11 and noticed that the ColorControl (9.8.2.1) app does not start as minimized. 
Thanks

**Comment by Synthesthesia** [comment]
Also having this issue.

**Comment by Maassoft** [comment]
Thanks for reporting this. This probably happened after I've placed the controls of the Options-tab in a separate component. Will be fixed in a future version.

**Comment by Maassoft** [comment]
Fixed with 9.9.0.0 or higher.
