### ISSUE TITLE
Question: What files/settings does ColorControl change to disable dithering on AMD

### ISSUE THREAD

**Issue by lextra2** [Maassoft/ColorControl#343]
What files/settings does ColorControl change to disable dithering on AMD?

I know old AMD GPUs supported a registry tweak like `HDMI_DisableDither` but that string was from `atikmdag.sys` which newer GPU drivers don't even ship with.

So how do you achieve disabling dithering on AMD in ColorControl?

**Comment by Maassoft** [comment]
ColorControl uses the ADL2 (AMD Display Library) to achieve this. You can find more info here: https://gpuopen-librariesandsdks.github.io/adl/group__DISPLAYAPI.html (See function [ADL2_Display_DitherState_Set](https://gpuopen-librariesandsdks.github.io/adl/group__DISPLAYAPI.html#ga057523cefb56aaabee51b67a9bd2a6d3))

Btw, does the AMD controller still work properly on your end? I thought there was a user saying it was broken a while ago. I currently can't test this myself.

**Comment by lextra2** [comment]
> Btw, does the AMD controller still work properly on your end? I thought there was a user saying it was broken a while ago. I currently can't test this myself.

Yeah it works. I haven't gotten any errors. 
Driver 24.3.1 on RDNA2 GPU

And thanks a lot for the quick reply. Very helpful information!
