### ISSUE TITLE
Option to Disbale Error Message

### ISSUE THREAD

**Issue by bluereaperx** [Maassoft/ColorControl#357]
I made a previous request a while ago to change the globally selected device to the last device that was turned on. That has worked great since, but I still get a ton of error messages when I try to change the volume with the wrong global device selected. I have to restart the app every time that happens otherwise it would keep sending error pop up messages for the next 2-3 minutes.

Can we have an option that disables that specific error message? Thanks.

![image](https://github.com/Maassoft/ColorControl/assets/118134592/c9420348-d4a5-413e-8fd4-8e0e4df67601)

**Comment by Maassoft** [comment]
v9.9.0.1 now contains this option.
