### ISSUE TITLE
Applying a non-HDR profile causes TV to remain in HDR despite Windows being in SDR

### ISSUE THREAD

**Issue by andre-ss6** [Maassoft/ColorControl#358]
Hi, I had a profile with HDR set to Included but without "Enabled" being set, like this:

![image](https://github.com/Maassoft/ColorControl/assets/15827357/65387220-c107-4ba9-983b-28126cae2417)

However, when going from a profile with HDR on to this one, even though Windows reports HDR as off, like so:

![image](https://github.com/Maassoft/ColorControl/assets/15827357/4f0be3f0-7404-4aff-aaa6-aa013760458f)

The TV remains stuck in HDR mode. The only thing I found that fixes it is restarting the PC (going back to HDR and then back to SDR did not fix it, nor trying to apply the profile that has everything set to default, or using NVCP, or restarting the TV only, none worked).

I'm on a LG C9 latest firmware, Windows 11 Pro 23H2, NVIDIA 552.12 RTX 4090

**Comment by AlM2025** [comment]
Make Sure you include the refresh rate

**Comment by andre-ss6** [comment]
> Make Sure you include the refresh rate

Refresh Rate is already included as in shown on the screenshot.
