### ISSUE TITLE
Random Pixel Appears on Desktop

### ISSUE THREAD

**Issue by Girafficonical** [Maassoft/ColorControl#360]
Honestly not sure how to diagnose or describe this issue. I updated to 9.9.0.1 and have had a random white pixel show up on my desktop. It seems to be some sort of ghosting based on the top left corner of the application's window. I can move it by snapping the ColorControl window to a location and restarting the program. I've provided some example images below:
![image](https://github.com/Maassoft/ColorControl/assets/99422588/793c6a9c-a152-4af9-9e01-110bfb652fdd)
![image](https://github.com/Maassoft/ColorControl/assets/99422588/b70a7dfe-5a88-46d3-8252-4be0a8a5e477)
![image](https://github.com/Maassoft/ColorControl/assets/99422588/b8cc2506-20ff-42c3-bd94-ec55383e8126)

**Comment by sebid** [comment]
If application is minimized, or in taskbar, it will appear like this in the Alt Tab, showing this pixel.
![image](https://github.com/Maassoft/ColorControl/assets/761115/b497add3-5438-470f-bb97-04f5220b3e29)

**Comment by sebid** [comment]
I also use Power Toys snap with a custom area and keep CC snapped in a corner :) Maybe you're onto something.

**Comment by Girafficonical** [comment]
Thanks for the chime-in. I got the name mixed up, it's called Windows Power Toys FancyZones just for correction. I tried turning off FancyZones and the dot does go away/not appear anymore. Looks like it is the cause of the pixel. I'll try to see if I can figure out which FancyZones setting is causing it, if any.
