### ISSUE TITLE
TV doesn't have time to execute NvPreset(HDR) AND pictureMode(hdrGame) fast enough to register the pictureMode change

### ISSUE THREAD

**Issue by Peskinator** [Maassoft/ColorControl#362]
Hi,

I just found out about ColorControl and i'm currently spending all my free time on this awesome program :)

As described here: https://github.com/Maassoft/ColorControl/issues/145#issuecomment-1335795866
I know I can't switch to an HDR picture mode without telling Nvidia to switch to HDR first.
But I think my TV doesn't have the time to do those: `NvPreset(HDR), pictureMode(hdrGame), hdrDynamicToneMapping(HGIG)` in a row.
(especially the first 2)
If I execute those manually, it works, but in sequence, it doesn't.
Does that make sense? Am I the only one?

Thank you!

**Comment by Maassoft** [comment]
You can add a delay in milliseconds after each step:

`NvPreset(HDR):2000, pictureMode(hdrGame), hdrDynamicToneMapping(HGIG)`

This will wait 2 seconds after executing the HDR step. It's a bit like a hidden feature😄

**Comment by Peskinator** [comment]
Fantastic, it works :)
Thank you, this is exactly what I needed to switch between a profile for gaming and a profile for Plex HTPC :)
