### ISSUE TITLE
Keyboard Shortcut for LG Gamebar

### ISSUE THREAD

**Issue by Daniel9132** [Maassoft/ColorControl#365]
Hello,
i would like to ask if there is a keyboard shortcut for the LG Gamebar Feature inside ColorControl.
I couldn't find any kind of keyboard shortcuts.
My goal was to find a simple way to adjust brightness. I was using ClickMonitorDDC with my old monitor.
Unfortunately it couldn't control the brightness on my LG 42C3.

Greetings

**Comment by Maassoft** [comment]
Yes, on the LG controller tab page there is a Settings... button which contains another Settings item. After you've clicked this, a dialog should open which contains the "Game Bar shortcut" (amongst other settings).

**Comment by Daniel9132** [comment]
Thank you very much!
