### ISSUE TITLE
Can you forcefully enable game HDR Basic + original preset in samsung tvs ? 

### ISSUE THREAD

**Issue by diolesinge** [Maassoft/ColorControl#373]
Hi Maassoft, first of all thanks for the tool.
I've been wondering since you managed to enable on lg displays hgig+color booster, if it was possible on samsung tvs to have the original preset in game mode (which is the most accurate) with the Game HDR basic (hgig equivalent) ? especially on the s95d.

if you enable the original preset game hdr is forcefully put to off. 
Thank you for the answer.

**Comment by Maassoft** [comment]
No, I don't think this is possible. The problem with the Samsung TV's is that I can only mimic remote control buttons and cannot change settings directly like with LG TV's.
Is the standard HDR Game mode on the S95D very over saturated like on the S95C? Then you can lower the Color setting to 15-18 and it will be a lot better.

**Comment by diolesinge** [comment]
No it's a bit more precise with the s95d, thanks for your answer tho, it's a bit sad they don't make both work altogether. 
i'm closing the issue.
