### ISSUE TITLE
novideo srgb doesn't launch at startup

### ISSUE THREAD

**Issue by suni03** [Maassoft/ColorControl#374]
When you right click on the tray icon after startup, novideo srgb will be missing until you launch it via colorcontrol 

Becomes a problem when switching between HDR and SDR as the clamp won't automatically enable/disable unless its been opened

**Comment by Maassoft** [comment]
What version are you using? Here with 9.9.0.1 the Novideo sRGB item is immediately visible in the tray menu after startup.

**Comment by suni03** [comment]
I'm an idiot - I didn't have the 'apply novideo srgb at startup' checked

Apologies and thank you for the wonderful software
