### ISSUE TITLE
Dithering type selector in preset menu is broken

### ISSUE THREAD

**Issue by AstralStorm** [Maassoft/ColorControl#38]
Dithering type selector for the preset is completely broken on nVidia.
(The Dithering -> Mode submenu.)
Selecting any mode but temporal chooses some sort of wrong value and also produces an error popup on the Options page when that is open with the preset highlighted.
The values on the Options page work correctly and as expected if the preset has Temporal selected.
This is likely a regression as older version of ColorControl did not have that issue - it exists in 3.2.3.0 and 3.3.0.0.

**Comment by Maassoft** [comment]
Thanks for reporting this. I've checked the code and to my surprise after changing the dithering type it tries to set the dithering bit depth instead of the mode. That's certainly a bug. Will be fixed in next release.

**Comment by Maassoft** [comment]
Fixed from 4.0.0.0.
