### ISSUE TITLE
v10.0.0.1 Not detecting .NET v8.0.7 (x64)

### ISSUE THREAD

**Issue by Amoeba00** [Maassoft/ColorControl#393]
When launching (even a clean install) of this latest version - I am getting prompted to install or update my .NET.
I have the latest version and even after re-installing/repairing it - I still get the prompt.
Any suggestions?
(FWIW, no issues at all running the latest v9)

**Comment by gnoby** [comment]
I have the same problem...

**Comment by Maassoft** [comment]
This version requires an additional package to be installed: the ASP.NET Core 8.0 Runtime (v8.0.7). Have you installed that? I've tested it on a VM and I got 2 popups: one for the .NET Desktop and one for ASP.NET Core.
This is the link for that package: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-8.0.7-windows-x64-installer?cid=getdotnetcore

**Comment by gnoby** [comment]
@Maassoft Thank you it works now!

**Comment by Amoeba00** [comment]
Ahh - ok - could those links be posted on the main page as a requirement?  I know I saw it - but didn't see the aspnet core name difference until you pointed it out.
Everything works (also, just did the latest firmware upgrade to 3.41 no issues there) - thanks for your continued efforts on this.
