### ISSUE TITLE
1.3.3.0 refuses to launch

### ISSUE THREAD

**Issue by laxu** [Maassoft/ColorControl#4]
I decided to upgrade to the latest and greatest, but it does not seem to launch at all. 1.2.0.0 works without a hitch.

**Comment by Maassoft** [comment]
That's strange, but another user (netjack7) has the same issue. I can however launch the app on several systems with no problem. I even reverted some code, but that still did not seem to help.
Is there any message in the Event Viewer?

**Comment by Maassoft** [comment]
I've tested 1.3.3.0 in a fresh Windows 10 VM (20H2) and it runs without any problem (except for the SmartScreen popup because of unknown publisher). I really am clueless why it won't work on your machine.
Have you tried running it as an administrator (should not be necessary)? What happens if you temporarily disable User Account Control?

**Comment by laxu** [comment]
I've tried running it as admin as well but no luck, it simply does not launch with no error.

**Comment by laxu** [comment]
Event viewer reports the following error:

P1: ColorControl.exe
P2: 1.3.3.0
P3: a0b972e7
P4: mscorlib
P5: 4.8.4250.0
P6: 5f2a052c
P7: 33d
P8: 2e
P9: System.ArgumentOutOfRange
P10:

**Comment by Maassoft** [comment]
Thanks for the log. I've created a new release with better exception logging. The exception logging itself could crash, so there would be no error popup visible. Hopefully the popup will be shown now, so it will give us more insight into the problem.

**Comment by laxu** [comment]
![image](https://user-images.githubusercontent.com/987972/100391561-87d53500-303c-11eb-8b94-d3c95e96d410.png)

**Comment by Maassoft** [comment]
Thanks for that screenshot, that helped me to find the bug. I've created a new release and hopefully you will be able to launch the application again.

**Comment by Maassoft** [comment]
This issue is now closed due to reports it's working again with 1.3.5.0.
