### ISSUE TITLE
Set shortcut without a modifer

### ISSUE THREAD

**Issue by roughavoc** [Maassoft/ColorControl#40]
I would like to be able to just press one key and for that to trigger a shortcut instead of having to use a modifier. Is this possible?

**Comment by Maassoft** [comment]
Maybe, but the input prevents it now. You could try manually changing the preset files here:

C:\Users\<username>\AppData\Roaming\Maassoft\ColorControl

But I'm not sure it works.

**Comment by roughavoc** [comment]
Thanks, setting the file to Read Only and inputting my own keys (F13-24) worked perfectly!
