### ISSUE TITLE
SDR Brightness Adjustment Error

### ISSUE THREAD

**Issue by simonboet** [Maassoft/ColorControl#407]
When adjusting SDR brightness on profiles I receive the following error.

![image](https://github.com/user-attachments/assets/7cf3f6de-5f4f-4048-84dc-61bd06e62d2d)

**Comment by pipohernandez** [comment]
same problem

**Comment by Maassoft** [comment]
Fixed with [10.0.2.0](https://github.com/Maassoft/ColorControl/releases/tag/v10.0.2.0)
