### ISSUE TITLE
Help! The connection is suddenly lost and cannot be recovered.

### ISSUE THREAD

**Issue by EHLLAM** [Maassoft/ColorControl#423]
The app was working fine for the past week with my 42C4, but today it suddenly showing the following error message: "Error executing Action: Not connected"

https://i.imgur.com/BdwdFrx.png

I've reset my PC and TV's Wi-Fi connection, deleted all the color control settings files in the Appdata folder, and reset my TV, but the app still won't work at all.

How can I fix this issue?

**Comment by EHLLAM** [comment]
NVM the issue just fixed like it happened.

**Comment by Maassoft** [comment]
Ok, then I'll close this. If you can reproduce it, create a new issue.
