### ISSUE TITLE
make colorcontrol more reliable? after standby-wakeup computer.

### ISSUE THREAD

**Issue by NeverBeLazyG** [Maassoft/ColorControl#424]
hey, first of all thank you very much for this awesome tool. i use it everyday. its so helpful.

I have a problem that keeps recurring. After I put my computer into standby mode and then woke it up again, color control doesn't work. I then have to restart it every time.

I tried different things. I installed it as a service or as a normal tray app. However, it kept happening that Color Control seemed to lose the connection to the TV. Only after restarting color control does it work again.

what can I do to make colorcontrol more reliable?

do you have some tips?

**Comment by Maassoft** [comment]
Do you also let ColorControl power on the TV on resume? Does that still work? If not, disable that and check if it works then.
Is there anything strange in the log visible at the time of sleeping/resuming?

**Comment by NeverBeLazyG** [comment]
can be closed, after updating to the latest version. its way more reliable. thanks
