### ISSUE TITLE
It seems there's no LG TV available! Please make sure it's connected to the same network

### ISSUE THREAD

**Issue by GrandisTectona** [Maassoft/ColorControl#43]
Hi 

I wonder if you could help. I have an LG C1, Rtx 3070, first when opening colorcontrol the LG TV not on network error came up, so checked Device Manager - Digital Media Devices and nothing was there, I had my TV connected with my router with ethernet, so I switched over to WiFi on the TV and then it shows in the device manager and in network (I'd prefer to just use ethernet). Problem is I still get the same error message when I open ColorControl. My Desktop PC is wired to the same router with ethernet, it doesn't have a WiFi card. But I shouldn't need to be using WiFi for both, right?

Kind Regards
Clive

![ColorControl Error](https://user-images.githubusercontent.com/89166154/130040524-92bceb84-9837-41fa-a2ca-954aceb7d61a.PNG)
![LG TV OLED Network](https://user-images.githubusercontent.com/89166154/130040531-54d7de9a-ad32-40c4-a21c-f75352262b95.PNG)
![LG TV Digital Media Devices](https://user-images.githubusercontent.com/89166154/130040534-f98da1fd-cecd-4b13-bf1f-bec832bc771f.PNG)

**Comment by Maassoft** [comment]
Hello, maybe this is because of the device filter that is set to "[LG]" by default (see LG controller tab). If you remove the brackets "[]", so that the device filter reads "LG" and click on Refresh, what happens then?

**Comment by GrandisTectona** [comment]
That's done the trick, It auto detects the LG TV now and I don't get the error. Does the direct mode to control the TV with a mouse and keyboard only work if you pair the LG TV remote as a Bluetooth device to the PC, I don't have a Bluetooth built-in or a dongle to test it. Cheers
Also on the Nvidia controller Tab, can you only adjust right click settings, by applying another profile, as the default/current settings are greyed out when right clicked on. Thanks for your help and building free apps for the community.

**Comment by Maassoft** [comment]
Yes, the direct mode simply uses the network connection to send keyboard/mouse input to the tv, no bluetooth needed.
The current settings item on the Nvidia controller tab is only for information, you can't change that one. You can alter all other presets via the context menu or "Change" button. Be sure to click on the "Included" item of a section, or the setting will not be applied. Default only the "Color settings" is included.

**Comment by GrandisTectona** [comment]
Brilliant thanks, my initial tests didn't work with direct mode, but I haven't had a proper chance to tinker with it.


I assume it's probably not possible to have the LG remote act as the mouse cursor, especially since your app is using the network connection or do you know of an application that could do this. I'm not complaining, I think pretty clever what you've already achieved.

**Comment by GrandisTectona** [comment]
That makes sense, I haven't had a chance to test it out properly yet.
 Now I know this probably isn't possible at all, but could the LG remote be used as a mouse cursor, ideally switching to a PC mode hdmi input would then act as a mouse.
Or are there any other programs that do this. Thanks

**Comment by Maassoft** [comment]
If I'm understanding you correctly, you want to control your pc with the LG remote? Maybe it would be possible if your pc has bluetooth and you could pair with your pc, but I'm not sure if that will work.

**Comment by Maassoft** [comment]
I've tested with 250% scaling and then the user interface gets indeed messed up, so that's a problem of the app and not on your end. After changing the scaling you must however sign out and sign in again (or restart the pc), otherwise the app won't see/respond correctly to the changes, even after restarting the app.
So I'm wondering if you change to 100-150% scaling and sign out of Windows and back in again, if you're able to manually add the tv via the "Add" button and enter the IP address (you can leave the Mac address blank). What happens then? Maybe the auto detect isn't correctly working on your C1 or there are other issues caused by Windows 11 or your environment, I can't say.

**Comment by GrandisTectona** [comment]
Color Control

Also to note my TV appears as 'LG TV OLED' in my 'Network', as when I set up my TV I changed it's name, that's why it could be different to your example, but I would of thought if that was the case, then it would autodetect as 'LG TV OLED' and not 'LG TV SSCR', I did see if I could reset this to default, but I can't unless I did a factory reset.
 
Testing to manually 'Add' the ip address, I have to many characters where I type the 3rd and 4th parts, I tried a few different combinations using LG TV SSCR and LG TV OLED for the TV name, with different layouts for parts 3 and 4, so 3 characters in each part of the ip address 
I'm sure this is normal, but I'm not sure how I should fill in those spaces.

![100% scale](https://user-images.githubusercontent.com/89166154/131232807-0b73286c-6c26-4aca-8c91-48d136af3122.jpg)

Cheers

**Comment by Maassoft** [comment]
It's indeed strange that you see "LG TV SSCR" instead of the device name under media/other devices. What do you see in Device Manager? Here it looks like this:
![image](https://user-images.githubusercontent.com/70057942/131251363-377accd7-e85d-4b0d-b593-6b93eab3a890.png)

When adding the tv manually the name doesn't matter and you don't have to fill in all the "underscored" spaces, just leave them blank.
Come to think of it, there's no IP address after the auto detected device, so maybe it detects the wrong device instance. If you change the device filter to "LG OLED", does it find a device then?

**Comment by GrandisTectona** [comment]
> Did you ever solve it? I have the same issue. Same tv but a 3080.

Yes, I just typed in LG OLED and it auto detects my TV.

**Comment by rojjter** [comment]
> 

hmmm, I just tried that and it didn't work. :(

**Comment by GrandisTectona** [comment]
I'm using version 4.5.0.0 of the app, you could try that.

**Comment by ehaynes99** [comment]
FWIW, I added it manually, and it worked fine.
* Open Windows Explorer
* Select "Network" on the left nav
* Find the device under "Other Devices" (mine showed up more than once for some reason, but they all work the same)
* Right click the device and select "Properties"
* You can copy/paste everything from here verbatim. No extra underscores or anything like the above comment
![manual-color-control2](https://user-images.githubusercontent.com/2187664/177675473-414403c8-b4f8-4901-97dd-ab60fadcf6c1.png)
