### ISSUE TITLE
[Feature Request] Powershell interface

### ISSUE THREAD

**Issue by MahmoudAlyuDeen** [Maassoft/ColorControl#44]
I'm trying to control my TV from my phone and I found a way to SSH to my computer and run Powershell commands from the iOS Shortcuts app.

Is there any way to run LG presets from Powershell? Doesn't have to be pretty, I'm fine hardcoding each preset index or ID

**Comment by Maassoft** [comment]
Yes, in version [2.2.0.0](https://github.com/Maassoft/ColorControl/releases/tag/v2.2.0.0) I've added command line support. That should enable you to apply presets from the command line, be it a basic cmd.exe shell or PowerShell, both should work.
