### ISSUE TITLE
Can't find Plex in the list of Applications

### ISSUE THREAD

**Issue by MahmoudAlyuDeen** [Maassoft/ColorControl#46]
Steps to reproduce:
- download Plex
- create a new LG preset
- Open the Application drop-down

Expected:
- Plex is on the list and can be selected

Actual:
- Plex is not on the list

Already tried:
- deleting the TV preset and running a fresh search
- refreshing the list of apps

**Comment by Maassoft** [comment]
There was a bug that the "Refresh" button of the apps did not sent a request to the tv to get a fresh list if the cached list exists (ip-address_listApps.txt). The button should work now with 4.2.3.0.
