### ISSUE TITLE
App scaled incorrectly

### ISSUE THREAD

**Issue by Mellified** [Maassoft/ColorControl#48]
3840x2160@60 HDR with 200% scaling I see this...
![image](https://user-images.githubusercontent.com/81110968/133151841-28d784e7-bd99-424b-b9ee-20790a80a993.png)

**Comment by Maassoft** [comment]
Wow, that looks horrendoes and is not supposed to look like that!
I know there are still some scaling issues with this app, but I don't exactly know what went wrong on your system.

Could you test if you change the compatibility of the executable, if scaling is improved?
You'll have to go to the properties of ColorControl.exe (via Explorer context menu) and then Compatibility tab:

![image](https://user-images.githubusercontent.com/70057942/133283405-f211e7c6-861d-4043-833f-940f8d785a9e.png)

Then click on "Change high DPI settings" and select the setting below:

![image](https://user-images.githubusercontent.com/70057942/133283575-c44e83b8-0c35-43b3-940e-af6d992deb52.png)

Press OK twice, (re)start ColorControl and hopefully it will look better.

**Comment by Mellified** [comment]
Switching to System (Enhanced) DPI scaling makes it work as expected.

**Comment by Maassoft** [comment]
Enhanced DPI (GDI) scaling is now the default as of version 5.0.0.0.
