### ISSUE TITLE
custom add tv not working

### ISSUE THREAD

**Issue by z826540272** [Maassoft/ColorControl#49]
im using 10.0.0.213 as my TV address
but when i type it in ,
it not working .
dlna ways works fine

please do not use a formatted input box

**Comment by Maassoft** [comment]
There's indeed an issue with IP addresses with less than 3 digits per segment, there will be spaces in between the digits. I will improve this in the next release.

**Comment by Maassoft** [comment]
Should work now without the masked edit.
