### ISSUE TITLE
Please add a remote control key panel

### ISSUE THREAD

**Issue by z826540272** [Maassoft/ColorControl#5]
Like this 
its useful and easy test
![remote (1)](https://user-images.githubusercontent.com/56025847/100722923-21656380-33fc-11eb-8a97-f091a9c7607e.png)

**Comment by Maassoft** [comment]
Thanks for the suggestion. I will consider adding this.

**Comment by Maassoft** [comment]
Version 3.0.0.0 has a remote control panel embedded, closing this issue.
