### ISSUE TITLE
quickly toggle between normal HDMI mode and PC mode does not work on c1

### ISSUE THREAD

**Issue by pioklo** [Maassoft/ColorControl#53]
Hi. I create an action to switch the mode, but nothing happens.
Maybe due to the fact that I have a C1 TV?
It can be fixed?
And you can add a switch
console mode - PC mode

Am I doing everything right?
<img width="601" alt="Screenshot_1" src="https://user-images.githubusercontent.com/84073799/135772259-83b908be-055d-450f-aa33-5f6ce0cc0517.png">

**Comment by Maassoft** [comment]
Yes, maybe this doesn't work on a C1. I'll have to look into this, maybe there's a solution somewhere.
Your preset is fine, the app "HDMI 1" is only needed if you really need to switch to HDMI 1 if you're using another input at that time.
What do you exactly mean with Console mode - PC mode? The label/icon "Console"? Console mode is just normal HDMI mode (not PC) and probably with the Game picture mode.

**Comment by pioklo** [comment]
> What do you exactly mean with Console mode - PC mode? The label/icon "Console"?

everything is correct. Where is the console icon. Only in this mode are all TV functions available when a PC is connected.
There is no color gradient in PC mode.
In console mode, you can watch movies with all TV functions.
The normal HDMI mode is not suitable for this.

**Comment by epsilon-a** [comment]
Doesn't work for me on C1 either

Being forced to manually do it whenever I want to watch a movie, since PC mode disables post processing and trumotion, really sucks

**Comment by xxTheGoDxx** [comment]
Doesn't work on my CX either.

BTW for everyone waiting for a fix, I use this to manually go through the menus on my CX and it has been working perfectly (well 95%) for months:

To switch HDMI 1 to HDMI mode:

BLUE:3000, UP:500, UP:500, UP:500, RIGHT:500, ENTER:500, DOWN:500, ENTER:1000, DOWN:400, LEFT:400, ENTER:1000, ENTER:500, UP:500, ENTER:1000, EXIT

To switch HDMI 1 to PC mode:

BLUE:3000, UP:500, UP:500, UP:500, RIGHT:500, ENTER:500, DOWN:500, ENTER:1000, DOWN:400, LEFT:400, ENTER:1000, DOWN:400, DOWN:400, DOWN:400, DOWN:400, DOWN:400, DOWN:400, DOWN:400, DOWN:400, DOWN:400, ENTER:500, UP:500, ENTER:1000, EXIT

**Comment by epsilon-a** [comment]
This is for C1.

Change HDMI4 to PC:

BLUE:2000, UP:500, UP:500, RIGHT:500, ENTER:1000, ENTER:1000, ENTER:1000, DOWN:500, DOWN:500, DOWN:500, DOWN:500, LEFT:500, ENTER:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, DOWN:500, ENTER:500, UP:500, UP:500, UP:500, UP:500, RIGHT:500, ENTER:500, EXIT

Change to regular HDMI:

BLUE:2000, UP:500, UP:500, RIGHT:500, ENTER:1000, ENTER:1000, ENTER:1000, DOWN:500, DOWN:500, DOWN:500, DOWN:500, LEFT:500, ENTER:500, ENTER:500, UP:500, UP:500, UP:500, UP:500, RIGHT:500, ENTER:500, EXIT

**Comment by pioklo** [comment]
5.0.1
function still doesn't work ...

**Comment by Maassoft** [comment]
Sorry, still looking through unpacked firmware files of the C1. Only thing I found so far is a config named "com.palm.app.settings.enableHdmiPcLabel". Maybe, just maybe setting this config with a "true"/"false" will switch the C1 to/from PC mode. I've tried it on my C9 but nothing happened (no errors either).
Is it still the dashboard where you have to change the input labels on the C1?

**Comment by epsilon-a** [comment]
> Sorry, still looking through unpacked firmware files of the C1. Only thing I found so far is a config named "com.palm.app.settings.enableHdmiPcLabel". Maybe, just maybe setting this config with a "true"/"false" will switch the C1 to/from PC mode. I've tried it on my C9 but nothing happened (no errors either). Is it still the dashboard where you have to change the input labels on the C1?

Yes it's done via the dashboard, the menu is just nested differently

**Comment by Maassoft** [comment]
I've created a new release 5.1.0.0 which now supports changing the "icon" of the HDMI 1-4 connections. Should also work on the C1.

**Comment by pioklo** [comment]
> I've created a new release 5.1.0.0 which now supports changing the "icon" of the HDMI 1-4 connections. Should also work on the C1.

Does not work. It breaks the icons in the settings, but does not change the mode.
![IMG_7164](https://user-images.githubusercontent.com/84073799/147655784-9f82f3db-3e66-41b6-847f-77f72a11bfe3.JPG)

**Comment by Maassoft** [comment]
Hmm, I've based this on the Home Connect code of the C1 firmware and it works on my C9 strangely enough. But maybe I've not specified some required parameters. There's an "activate" and "forceIcon" parameter that possibly must be set to "true", I don't know. I've left out the "label" as well, maybe that's why it's shown as a dash in your picture.

**Comment by pioklo** [comment]
> Hmm, I've based this on the Home Connect code of the C1 firmware and it works on my C9 strangely enough. But maybe I've not specified some required parameters. There's an "activate" and "forceIcon" parameter that possibly must be set to "true", I don't know. I've left out the "label" as well, maybe that's why it's shown as a dash in your picture.

This parameter changes HDMI name to " - ". And it shows the mode that was selected through the program, but does not change it.

**Comment by epsilon-a** [comment]
> I've created a new release 5.1.0.0 which now supports changing the "icon" of the HDMI 1-4 connections. Should also work on the C1.

It's working perfectly on the C1

Thanks

**Comment by epsilon-a** [comment]
By the way, is it possible to change the TV speaker preset through the app?

C1 is plagued by a bug where the speakers always default to GAME OPTIMIZER sound preset (that is garbage) if you have gsync enabled.

**Comment by pioklo** [comment]
> > I've created a new release 5.1.0.0 which now supports changing the "icon" of the HDMI 1-4 connections. Should also work on the C1.
> 
> It's working perfectly on the C1
> 
> Thanks

this does not work

**Comment by epsilon-a** [comment]
> > > I've created a new release 5.1.0.0 which now supports changing the "icon" of the HDMI 1-4 connections. Should also work on the C1.
> > 
> > 
> > It's working perfectly on the C1
> > Thanks
> 
> this does not work This changes the icon but does not change the mod

Works just fine.

**Comment by pioklo** [comment]
> Works just fine.

please make a video

**Comment by epsilon-a** [comment]
> > Works just fine.
> 
> please make a video

Why would I bother doing that?
I went through the trouble of figuring out the steps to manually change it via the app and shared it a while ago, now with this update it works, you think I'm just making things up for fun?
The labels are all correct and I can see the difference in chroma resolution right away once the screen flashes black.

**Comment by pioklo** [comment]
> Why would I bother doing that?

Because it doesn't work. It cannot be that it works for you but not for me. You don’t understand that the name and icon are changing, but not the mode.

**Comment by pioklo** [comment]
> Why would I bother doing that?

Okay. My fault. I figured out what the problem is. It works. But not correct. It changes the mode, but does not change the name of the mode if you press the wheel. This was the confusion.

**Comment by Maassoft** [comment]
Yes, currently I do not update the label, but it seems it will just overwrite the actual label with a blank string. In the next version I will correct this.

**Comment by pioklo** [comment]
Found a new problem. After turning off and on the TV, HDMI changes to standard HDMI. Probably due to the fact that the modes are not switched correctly.

**Comment by Maassoft** [comment]
I've created a new version (5.2.0.0) which now sets the label (name) properly. Maybe it fixes that last issue too.

**Comment by pioklo** [comment]
> I've created a new version (5.2.0.0) which now sets the label (name) properly. Maybe it fixes that last issue too.

Works fine now. Thank you for your work!
