### ISSUE TITLE
Service menu access? How?

### ISSUE THREAD

**Issue by javsp** [Maassoft/ColorControl#57]
I've read this app can access to the service menu of my LG OLED C1 by making a macro.  Unfortunately I couldn'f find more info about it. Is this posible? How?

**Comment by Maassoft** [comment]
It should be possible as long as the tv lists the "com.webos.app.factorywin" app. The friendly name on my C9 is "QML Factorywin", but that could be different on a C1. Here's a screen shot of my preset:
![image](https://user-images.githubusercontent.com/70057942/142039816-ccaa8751-ae71-4992-8e8d-f55b726fc7fa.png)
So just use Add to create a new preset, fill in a name, select the "QML" app from the dropdown and optionally fill in the steps to let ColorControl automatically send the password. Click Save and then Apply to launch the service menu.
Currently only the "InStart" service menu can be accessed through my app, but that's where you find the most interesting settings.

**Comment by javsp** [comment]
I confirm this method also works for the C1 model.

Thanks!
