### ISSUE TITLE
ColorControl 5.0.0.0: missing frameworks for .NET

### ISSUE THREAD

**Issue by javsp** [Maassoft/ColorControl#63]
I updated the app today and I get this error when I execute it:

![cc](https://user-images.githubusercontent.com/33856667/147484158-4062b6c0-b43b-4bbb-9e9f-8ce7cbb01024.png)

I've already installed the .NET 6.0 Runtime. What am I missing?

**Comment by Maassoft** [comment]
I was able to reproduce this on a VM. It seems the app needs the ASP.NET Core 6.0 Runtime as well.
You can download it here: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.1-windows-x64-installer

I will try to remove this dependency in the next version.

**Comment by javsp** [comment]
I installed the ASP.NET Core 6 Runtime and I keep getting the same error. I'm on Win11 if it matters.

**Comment by Maassoft** [comment]
I've created a 5.0.1.0 release which has all unnecessary dependencies removed. Please try if that works.

**Comment by javsp** [comment]
It's working now. This is the only required installer to run this new version. Thanks.

**Comment by Amoeba00** [comment]
> It's working now. This is the only required installer to run this new version:
> 
> https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.1-windows-x64-installer
> 
> Thanks.

Yup.  Same here.

**Comment by Maassoft** [comment]
Thanks for the feedback.
