### ISSUE TITLE
Dethering settings are not saved

### ISSUE THREAD

**Issue by pioklo** [Maassoft/ColorControl#67]
After restarting the computer, the setting is reset to enabled 6 bits.

**Comment by Maassoft** [comment]
The settings are saved, but there's currently no documented way to read the current settings through the Nvidia API (other then reading from registry, but that requires admin rights). What has changed from 5.0.0.0 is that as soon as you open the Options-tab and it can not derive the settings from the latest executed preset, it defaults to 6-bit temporal dithering in SDR instead of 8-bit. For my C9 6-bit is better for gradients (it's more aggressive). Under HDR it defaults to 8-bit because 6-bit generates too much noise.

**Comment by pioklo** [comment]
> Options-tab and it can not derive the settings from the latest executed preset

Did I understand correctly that I shouldn't go into the settings?
6 bit makes noise yes. I thought my TV broke when I saw it :)

**Comment by Maassoft** [comment]
If you open the Options-tab page it can change the settings, yes.
But I've created a new release (5.2.0.0) and refined this a little bit. It looks now for the lowest used bit depth of your presets and as long as you don't have any for 6-bit, it won't revert to that.
By the way, is 6-bit temporal dithering really so easy to see in SDR? I hardly notice it and I'm 2 feet/0.5 meter from the screen :)

**Comment by pioklo** [comment]
> so easy to see in SDR

HDR

**Comment by pioklo** [comment]
> t looks now for the lowest used bit depth of your presets and as long as you don't have any for 6-bit, it won't revert to that.

Can get more details pls? I am using unlocked 12 bit. After restarting the program, it still resets to 6 bits ...

**Comment by Maassoft** [comment]
With 12-bit you mean the color depth and not the dithering bit depth? There's no 12-bit dithering. Dithering is not automatically changed on startup of the program, unless you have a preset configured to start on startup.
Note that Nvidia dithering settings seem to be persistent over a reboot of Windows, so you can just set them one time and forget about them, unless you prefer different settings for HDR and SDR, which I do. Higher bit depth of dithering doesn't mean it's better anyway, generally it's more effective if its bit depth is lower than the color bit depth.

**Comment by pioklo** [comment]
> so you can just set them one time and forget about them,

ok

**Comment by Maassoft** [comment]
With version 5.3.0.0 this issue should be resolved now. Can you confirm this?

**Comment by pioklo** [comment]
> With version 5.3.0.0 this issue should be resolved now. Can you confirm this?

Yes, now everything is working as it should. Thanks again for solving problems quickly.
