### ISSUE TITLE
Reading dither settings via NVAPI

### ISSUE THREAD

**Issue by ledoge** [Maassoft/ColorControl#68]
Hi,
I figured out how to use `NvAPI_Disp_GetDitherControl`. Your `NV_GPU_DITHER_CONTROL_V1` struct is missing two 32 bit fields at the end, which I'm pretty sure are flags for the supported dither bit depths and modes respectively. Accordingly, the `version` field needs to be set to `0x10018` (version 1, and a size of 0x18 bytes). With those two changes the call should work. You can also look at my implementation [here](https://github.com/ledoge/novideo_srgb/blob/master/novideo_srgb/Novideo.cs).

**Comment by Maassoft** [comment]
Thanks a lot! I was looking for an implementation for over 2 years or something. I couldn't find it anywhere.
I've just tried your suggestions and it works!
Where did you get the info of the version field and other fields? I've looked at some older NvApi files, but only found a struct named "NV_GPU_DITHER_CONTROL_V1" but didn't know the composition. Those NDA's are a pain the *ss, lol.

**Comment by ledoge** [comment]
The version field stuff is just something I was familiar with from previously working with NVAPI. After using the right value to represent the size + version, the call was still returning `-9` (`NVAPI_INCOMPATIBLE_STRUCT_VERSION`), so I knew the size of the struct was actually wrong. After adding those extra fields and setting the size appropriately, it returned `0` instead, so I knew it was right :).

As to what those extra fields actually mean, them being flags for supported features is an educated guess based on the fact that they are `0b111` and `0b11111` respectively on my GPU, and the number of set bits matches exactly with the available bit depth and mode options.

**Comment by Maassoft** [comment]
Ahh, thanks for the information. It's almost ridiculous that these functions are undocumented and we have to go to these lengths to be able to calling them.
Anyway, I've released a new version of the app which has the fix incorporated and the workarounds removed.
