### ISSUE TITLE
No more access to the service menu?

### ISSUE THREAD

**Issue by javsp** [Maassoft/ColorControl#69]
I have this script in order to enter in the service menu:

![Sin título](https://user-images.githubusercontent.com/33856667/148259898-82e7c4c8-f4e1-419b-8cb1-7f6a561ba1a3.png)

So far it has worked perfectly but today I can't access to that menu. I don't know if it's something related to ColorControl or the TV itself (firmware).

Any help?

UPDATE: I've tried it with an older version of ColorControl (4.5.0.0) and it works so it's something related to the newer versions of the app.

**Comment by Maassoft** [comment]
Have you checked this check box on the Options-tab page?
![image](https://user-images.githubusercontent.com/70057942/148271770-66601ceb-1a36-4507-8b19-d8224b4b095f.png)

I probably should've mentioned this in the release notes, but manual presets for the InStart and Software Update app (with downgrade possibility) now only function properly after this check box is checked. Once it's checked, you can also access the InStart (and EzAdjust) service menu through the "Expert" button:
![image](https://user-images.githubusercontent.com/70057942/148272275-04402486-b325-404f-bad6-66adacaa5090.png)

**Comment by javsp** [comment]
Yeah, that was the problem. It works fine now. Is there any risk for the TV if you have this option permantly enabled?

**Comment by Maassoft** [comment]
No, the app won't do anything with these service menus automatically unless you open them yourself.

**Comment by javsp** [comment]
Perfect, thanks.
