### ISSUE TITLE
1.3.6

### ISSUE THREAD

**Issue by netjack7** [Maassoft/ColorControl#7]
For some strange reason, it doesn't startup with win startup even though I have checkbox checked.

**Comment by Maassoft** [comment]
Did it create a scheduled task? Open Task Scheduler and you should see a task like this:
![image](https://user-images.githubusercontent.com/70057942/101291578-2d8d5e80-380a-11eb-87aa-6f1bc7c5836e.png)
It should also show the Last Run Time and Last Run Result (which should be something like "Completed successfully. (0x0)").

**Comment by netjack7** [comment]
It's there. But man is it hit or miss. Sometimes it just doesn't start.
I'll keep an eye on it.

**Comment by netjack7** [comment]
It doesn't stick (device filter is often empty):

[image: image.png]

**Comment by Maassoft** [comment]
For some reason I can't see your screenshots. Can you check in LgConfig.json if the setting "DeviceSearchKey" has some value (the value you entered)? Here it contains "C9" and it is shown in the user interface as well.

**Comment by Maassoft** [comment]
Closing this issue because settings should now be saved properly.
