### ISSUE TITLE
Suggestion. Support for LG sound bars.

### ISSUE THREAD

**Issue by PsYchitOut** [Maassoft/ColorControl#71]
This might be a little far out in the weeds for you to seriously consider, but it would certainly make my life easier.

As a way of bypassing the Earc audio delay issue on my LG C1 I have a separate HDMI cable going to the pass through port on the sound bar, which is a LG SN9YG and I use Earc for everything else. Which means I have to flip the input on the device when using my PC. 

Magic remote controls work just fine for basic things like adjusting the volume. However, the only way you can change the input  is either with the original remote, the LG soundbar app which is separate from the webos app (because of course it is) or *gasp pressing the input button on the soundbar itself.

It would be nice to be able to send a remote command out using only a keystroke.

**Comment by Maassoft** [comment]
Thanks for the suggestion. You're right that this is a bit far fetched to support. And I don't have a LG sound bar to test it on.
But I've found a Python project on GitHub that might support your use case: https://github.com/google/python-temescal

With this you could probably change the input with 'set_func':

```
import temescal

speaker = temescal.temescal("192.168.1.15", callback=speaker_callback)
speaker.set_func("HDMI2")
```

**Comment by PsYchitOut** [comment]
That's actually pretty dead on with what I'm looking for. Now I just have
to dust off my knowledge of python and get started.

Thanks again for the help.
