### ISSUE TITLE
Hold down Ctrl on restart to prevent power off doesn't work

### ISSUE THREAD

**Issue by javsp** [Maassoft/ColorControl#72]
I've checked the "Automatically power off on shutdown" option in ColorControl. If I've understood it correctly this app shouldn't power off the TV as long as I hold down the Ctrl key when I select "restart Windows". However the TV is always powered off. Does this feature work or I'm doing something wrong?

**Comment by Maassoft** [comment]
No, you're doing nothing wrong, it's not working properly. Sometimes it does work, but more often it somehow gets ignored.
It's a shame there's not a proper way to detect if Windows is shutting down or restarting. The enum "SessionEndReasons" only defines a Logoff and SystemShutdown, no restart. Windows does log something in the Event Viewer on restart, but then it's already too late.
I'll try if I can improve the Ctrl-key functionality.

**Comment by javsp** [comment]
Yeah but despite of the lack to detect if the user restarts or shuts off the system it's a nice idea to skip the power off process by holding down a key. Maybe if you map another different key? I don't know Ctrl but the Shift key, for example, is reserved by Windows when you click on restart the system.

**Comment by Maassoft** [comment]
Fixed by the delay when shutting down/restarting pc in 5.5.0.0.
