### ISSUE TITLE
Nvidia Controller tab missing on version 5.2.0.0 and newer

### ISSUE THREAD

**Issue by Joshaze** [Maassoft/ColorControl#75]
The Nvidia Controller tab is missing on all versions of ColorControl 5.2 and higher.
The 

5.0.1.0 (Nvidia Controller tab present):
![image](https://user-images.githubusercontent.com/63926402/153766796-5da7d92f-a5f1-4c41-8717-8325a13988c3.png)

5.0.1.0 Log:
![image](https://user-images.githubusercontent.com/63926402/153766777-76c8214d-44ba-4e09-b752-ff76d51234c1.png)

5.0.1.0 Info:
![image](https://user-images.githubusercontent.com/63926402/153766575-5c91fb39-1d26-48d1-9f3e-c46cfcb76919.png)

-----

5.2.0.0 Log (Nvidia Controller tab missing):
![image](https://user-images.githubusercontent.com/63926402/153766709-9bd4cfcb-5e46-47d7-9613-7703c5980ac4.png)

5.2.0.0 Info:
![image](https://user-images.githubusercontent.com/63926402/153766730-4721e6a5-a06f-4960-944e-9a05f14022d4.png)

-----

5.4.0.0 Info (Nvidia Controller tab missing):
![image](https://user-images.githubusercontent.com/63926402/153767060-8d057be2-0f5e-4c75-ad30-28aeb3a87837.png)

-----

Nvidia Control Panel - System Information:
![image](https://user-images.githubusercontent.com/63926402/153766853-9867dad6-056c-429d-a8e6-9e5b043aadbe.png)

-----

Display is a LG-C9 with Software Version 05.25.09

**Comment by Amoeba00** [comment]
Could be something with your system.  You might need to clear out all your info and refresh.

Try closing the app, renaming the ControlControl folder in here : %AppData%\Roaming\Maassoft, then restarting ColorControl.

(you could delete, but safer to rename first, then delete later)

![image](https://user-images.githubusercontent.com/39176113/153768387-3072e6e6-f78a-4fe1-b7d4-e0282b910a8f.png)

**Comment by Maassoft** [comment]
I think Amoeba00 is right. There's probably something wrong with your 'NvPresets.json' file (see previous post for location).
Before deleting, can you attach it here so I can analyze it? Maybe it's a specific scenario that's not handled well when saving/loading the .json files.

**Comment by Joshaze** [comment]
Rebuilding the "%AppData%\Roaming\Maassoft" directory fixed the issue. Thank you
[NvPresets.json.txt](https://github.com/Maassoft/ColorControl/files/8103889/NvPresets.json.txt)
! previous NvPresets.json file attached.

Thank you.  I appreciate you!
