### ISSUE TITLE
Colour Gamut: Native option missing under Expert settings

### ISSUE THREAD

**Issue by Canzah** [Maassoft/ColorControl#78]
Greetings,
On LG C1 TVs there's an additional option for Colour Gamut called "Native", it replaced the "Wide" option from older TVs, but is not the equivalent of Wide setting and the "Wide" setting is actually separate from "Native" (and "Wide" seems to not do anything on the C1, as it's not normally accessible without this app).
I'd like to request the addition of the "Native" option to the Expert settings under Colour Gamut options.

**Comment by Maassoft** [comment]
I'll add this in the next release. I've found the setting in the source code of the settings app of the C1. It did nothing on my C9, but that was expected.

**Comment by Canzah** [comment]
Thank you very much, it makes a significant difference in colours on the C1 so I'm looking forward to it.
Is there any ETA for when next release might happen?

**Comment by Maassoft** [comment]
I've just released 5.5.0.0 which contains this setting.
