### ISSUE TITLE
Preventing powering off the tv when restarting the pc (5.5.0.0)

### ISSUE THREAD

**Issue by javsp** [Maassoft/ColorControl#79]
If I'm not wrong you can set a shutdown delay in this version in order to know if the user restarts or shutdowns the PC. So, if the user just restarts the PC then the TV doesn't power off. The thing is I've tried different values and the TV is always powered off unless I set a shutdown delay of 4500+ ms, in which case the TV is never powered off (even if I shurdown the PC).

Reading the changelog it seems the app is waiting for a concrete Event ID. I guess it never happens. I'm using W11 Pro (everything is updated).

**Comment by Maassoft** [comment]
I'm using W11 Pro as well, fully updated. Do you see the event 1074 under System in the Event Viewer?
It should have these contents:
```
The process C:\WINDOWS\Explorer.EXE (<computername>) has initiated the restart of computer <computername> on behalf of user <username> for the following reason: Other (Unplanned)
 Reason Code: 0x0
 Shutdown Type: restart
 Comment: 
```
And it's the shutdown type what I'm checking for (restart or power off). If you look at the log of ColorControl the contents should be there as well (if it's detecting the event). Do you have Windows in English or another language?
The reason a delay is even needed is that Windows tries to close my app just before the event is even logged in the event viewer. The app can block closing for maybe 5 seconds, but then it's probably forcibly closed. That's probably what happens with too long delays and what you're seeing then.

**Comment by javsp** [comment]
I have Windows in Spanish. Could it be the reason why it doesn't work?

I think this is the Event you're referring to:

![Sin título](https://user-images.githubusercontent.com/33856667/155856336-a4d71a6e-ec80-4710-bb8d-310fa9085073.png)

**Comment by Maassoft** [comment]
Yes, that's it! So 'Reinicio' means a restart and what is a power off?
I'll add the Spanish names in the next version and that it should probably work.

**Comment by Maassoft** [comment]
I've created v5.5.1.0 which now also checks for these names. Hopefully this works.

**Comment by javsp** [comment]
It works now. Thanks!

I'm using the default shutdown delay value (1000 ms).
