### ISSUE TITLE
Feedback: Revise the readme (request).

### ISSUE THREAD

**Issue by MintyTrebor** [Maassoft/ColorControl#8]
Great app, works well, but I had a few setup issues which I think could have been avoided by updating the readme with the following:

For the API TV Control:
Check the TV is listed in windows Device Manager (win+x -> device manager) under Digital Media Devices. If not then add the TV using windows "All Settings" -> "Devices" -> "Add bluetooth or other device" -> "Everything Else", then select your TV by name. It should now appear in Device Manager. (If your TV is not shown when adding devices then your PC is unable to see the TV on the network, check your network settings on both the PC & TV) 
NOTE: You may have to add the TV as a device more than once before it appears in Device Manager, as windows can detect the TV as multiple devices.

If you receive WinPcap errors download and install Npcap (https://nmap.org/npcap/#download) in WinPcap compatibility mode. WinPcap is depreciated under windows 10.

Thanks!

**Comment by Maassoft** [comment]
Thanks for the feedback, I've updated the readme and added your text.
Happy new year!
