### ISSUE TITLE
"Could not refresh apps" when using power on after startup

### ISSUE THREAD

**Issue by chonzytron** [Maassoft/ColorControl#90]
![imagen](https://user-images.githubusercontent.com/71772046/160285704-6c9e0135-3b03-4978-860c-2cb22df7f4b1.png)

On my LG C1 everything works as intended, and the TV starts remotely with windows, except I get this message every time I log in.
Also the shortcuts for the LG controller actions only work sometimes, unlike the AMD controller settings, where the shortcuts work every time.

Thank you for your work!

**Comment by Maassoft** [comment]
Maybe there's an issue with the newer series TV's when the list of all installed apps is requested. Does the same error occur when you manually click this "Refresh" button:
![image](https://user-images.githubusercontent.com/70057942/160453075-795dbf27-f68e-46c5-a9c7-0493cc4ac657.png)

**Comment by chonzytron** [comment]
thanks for the reply, it works:
![imagen](https://user-images.githubusercontent.com/71772046/160455110-272a2994-e814-42d1-9873-81aa4a9b2260.png)

**Comment by clotobee** [comment]
> Maybe there's an issue with the newer series TV's when the list of all installed apps is requested. Does the same error occur when you manually click this "Refresh" button: ![image](https://user-images.githubusercontent.com/70057942/160453075-795dbf27-f68e-46c5-a9c7-0493cc4ac657.png)

@Maassoft when clicking on "Refresh" the app list is there but I'm getting the warning message everytime I log in nonetheless :(

Thanks for the reply

**Comment by chonzytron** [comment]
> > Maybe there's an issue with the newer series TV's when the list of all installed apps is requested. Does the same error occur when you manually click this "Refresh" button: ![image](https://user-images.githubusercontent.com/70057942/160453075-795dbf27-f68e-46c5-a9c7-0493cc4ac657.png)
> 
> @Maassoft when clicking on "Refresh" the app list is there but I'm getting the warning message everytime I log in nonetheless :(
> 
> Thanks for the reply

same

**Comment by Maassoft** [comment]
Maybe the list is requested too soon and the TV is still "starting up". I can probably fix this by adding a delay. I think I'll also remove the warning dialog in this case and write any errors to the log file. Will be fixed in the next release.

**Comment by clotobee** [comment]
> Maybe the list is requested too soon and the TV is still "starting up". I can probably fix this by adding a delay. I think I'll also remove the warning dialog in this case and write any errors to the log file. Will be fixed in the next release.

Good to know bro, thanks a lot for your work 🙏🏻

**Comment by Maassoft** [comment]
I just released version 5.7.0.0, this should fix the message on startup.

**Comment by chonzytron** [comment]
no more dialog, thanks man!

**Comment by Maassoft** [comment]
Fixed in 5.7.0.0.
