### ISSUE TITLE
Will not start after nvidia driver update and clean install of Color Control

### ISSUE THREAD

**Issue by nzae** [Maassoft/ColorControl#91]
Hi,

Recently after the driver update I haven't been able to get ColorControl to launch at all. This error message is reported (see below). Please let me know if there is any other information that I can provide. 
![image](https://user-images.githubusercontent.com/65926944/160310121-cfbe60fa-81ee-49e0-9c65-0d6f58622317.png)

**Comment by Maassoft** [comment]
I think your Settings.json file might be corrupt. Could you check this folder and rename/remove it?
`C:\Users\<username>\AppData\Roaming\Maassoft\ColorControl`

**Comment by nzae** [comment]
Thank you! That did work to get the program to open again. however trying to go into LG controller tab always gives this error.
![image](https://user-images.githubusercontent.com/65926944/160513495-a8040aac-0de9-4ef3-9938-00d2fffeafa2.png)
Any other suggestion?

**Comment by Maassoft** [comment]
Can you do the same with the LgConfig.json file? I think that one is corrupt as well. If it still fails, delete the LgPresets.json too.

**Comment by nzae** [comment]
Thank you, I deleted both and it is working again.

**Comment by Maassoft** [comment]
Version v5.7.0.0 now betters detects corrupt config files and will generate a new one.
