### ISSUE TITLE
NVAPI_NOT_SUPPORTED when switching Hz and BPC

### ISSUE THREAD

**Issue by jmf866** [Maassoft/ColorControl#95]
I get this error in certain scenarios.
SetColorData threw an exception: NVAPI_NOT_SUPPORTED

I want to apply on startup 30Hz and BPC12.
If the refresh rate is currently at 60Hz (or anything that does not support > BPC 8), the error is thrown.  Refresh is changed to 30Hz but BPC is not changed.
Would it be possible to change the refresh rate first, and then change the BPC?

**Comment by Maassoft** [comment]
Currently it's not possible (apart from having 2 separate presets executed in succession), but I think I can make some changes so this would work better. Problem of course is that if you switch to a higher refresh rate, the bit depth has to be lowered first. So it must work in both directions:
New refresh rate lower than current: apply refresh rate first, then color settings.
New refresh rate higher than current: apply color settings first, then refresh rate.

**Comment by jmf866** [comment]
That sound great, thanks!

**Comment by jmf866** [comment]
I found a satisfactory alternative by configuring steps on the LG Controller tab.  Even though my LG is not connected to the network, this tab can be used if "Allow triggers to be fired for this device" is disabled.

I just have these steps enabled when my HTPC software starts, to run two Nvidia presets sequentially.
NvPreset(30Hz), NvPreset(BPC12)

**Comment by Maassoft** [comment]
Nice workaround! I've just released v5.7.1.0 though, which should fix the exception you've encountered.

**Comment by jmf866** [comment]
This works perfectly now, and is independent of applications starting up.  Thanks!
