### ISSUE TITLE
Steps for TV Turn On?

### ISSUE THREAD

**Issue by karamanliev** [Maassoft/ColorControl#98]
Is it possible to use the steps in LG Controller so I send a command only to power on the TV? Like an if-else or something?

What I've only found is the option to toggle the TV's power, which means that if the TV is ON it will turn off itself, which I don't really want to happen.

**Comment by Maassoft** [comment]
You can't use an if-else condition, but with the action "WOL" (Wake-On-Lan) you can power on the TV.

**Comment by karamanliev** [comment]
It works exactly as I've wanted. Big thanks for this great project!
